"""logos-bridge: a Python client for logos-json-rpc-bridge.

Async core (:class:`AsyncBridgeClient`) with a blocking mirror (:class:`BridgeClient`),
an HTTP client (:class:`BridgeHttpClient`), and a protocol-faithful fake bridge in
:mod:`logos_bridge.testing`. :mod:`logos_bridge.lidl` models LIDL contracts and
:mod:`logos_bridge.lidl_sources` reads them from files, packages and bridges.
"""

from __future__ import annotations

from ._protocol import DEFAULT_HTTP_URL, DEFAULT_URL, SUBPROTOCOL
from ._version import __version__
from .client import AsyncBridgeClient
from .compat import CompatReport
from .codec import (
    REJECTION_CODES,
    as_provider_rejection,
    decode_bytes_tag,
    decode_bytes_tags,
    encode_args,
    encode_bytes_tag,
    is_bytes_tag,
    is_logos_result,
    unwrap_result,
)
from .digest import canonical_json, contract_sha256, interface_sha256, shape_sha256
from .errors import (
    ArgumentError,
    ArityError,
    BlockingCallInEventLoop,
    BridgeError,
    BridgeWarning,
    BytesDecodeError,
    CallNotDispatched,
    Cancelled,
    ClientRejection,
    ClientTimeout,
    ConnectError,
    ConnectionClosed,
    DecodeError,
    DiscoveryPending,
    EventDecodeError,
    HttpStatusError,
    IncompatibleModule,
    InvalidParams,
    InvalidRequest,
    MethodNotExposed,
    MethodNotFound,
    ModuleResultError,
    ModuleUnavailable,
    NotAuthorised,
    Overloaded,
    ParseError,
    PortalStopped,
    ProviderRejection,
    RequestTooLarge,
    ResultDecodeError,
    RpcError,
    ShuttingDown,
    SubscriptionClosed,
    SubscriptionOverflow,
    SubscriptionTerminated,
    UpstreamCallFailed,
    UpstreamTimeout,
    UntypedModule,
    UpstreamTransportError,
)
from .http import BridgeHttpClient
from .models import CrossCheck, CrossCheckFinding, Event, Exposure, Health, InvalidParamsDetail, ModuleInfo
from .portal import BlockingPortal, PumpHandle
from .subscription import AsyncSubscription, SubscribeRequest
from .sync import BridgeClient, Subscription
from .dynamic import BlockingDynamicModule, DynamicModule
from .typed import LogosResult

__all__ = [
    "DEFAULT_HTTP_URL",
    "DEFAULT_URL",
    "REJECTION_CODES",
    "SUBPROTOCOL",
    "ArgumentError",
    "ArityError",
    "AsyncBridgeClient",
    "AsyncSubscription",
    "BlockingCallInEventLoop",
    "BlockingDynamicModule",
    "BlockingPortal",
    "BridgeClient",
    "BridgeError",
    "BridgeHttpClient",
    "BridgeWarning",
    "BytesDecodeError",
    "CallNotDispatched",
    "Cancelled",
    "ClientRejection",
    "ClientTimeout",
    "CompatReport",
    "ConnectError",
    "ConnectionClosed",
    "CrossCheck",
    "CrossCheckFinding",
    "DecodeError",
    "DiscoveryPending",
    "DynamicModule",
    "Event",
    "EventDecodeError",
    "Exposure",
    "Health",
    "HttpStatusError",
    "IncompatibleModule",
    "InvalidParams",
    "InvalidParamsDetail",
    "InvalidRequest",
    "LogosResult",
    "MethodNotExposed",
    "MethodNotFound",
    "ModuleInfo",
    "ModuleResultError",
    "ModuleUnavailable",
    "NotAuthorised",
    "Overloaded",
    "ParseError",
    "PortalStopped",
    "ProviderRejection",
    "PumpHandle",
    "RequestTooLarge",
    "ResultDecodeError",
    "RpcError",
    "ShuttingDown",
    "SubscribeRequest",
    "Subscription",
    "SubscriptionClosed",
    "SubscriptionOverflow",
    "SubscriptionTerminated",
    "UpstreamCallFailed",
    "UntypedModule",
    "UpstreamTimeout",
    "UpstreamTransportError",
    "__version__",
    "as_provider_rejection",
    "canonical_json",
    "contract_sha256",
    "decode_bytes_tag",
    "decode_bytes_tags",
    "encode_args",
    "encode_bytes_tag",
    "interface_sha256",
    "is_bytes_tag",
    "is_logos_result",
    "shape_sha256",
    "unwrap_result",
]
