# GENERATED by logos-bridge-codegen. Do not edit: regenerate instead.
# Contract: mini_module 0.1.0
# INTERFACE_SHA256: 589b01b9cbf84ab916d6d804868780c7c0e5d92063ee3b60061a55f330ff42ca
# CONTRACT_SHA256: 68bde1680866ea0e450ed711e334e8c70013110eddb8889887cba029232e1f7c
# SHAPE_SHA256: 14ae748c17d28fc9a8b1e741476849284cc38d75ba88c90c23a95c7c453bc8c0
# Codegen format: 1
# Regenerate: nix run .#regen-goldens
# Source: lidl tests/fixtures/lidl/mini_module.lidl
# Generator: logos-bridge 0.1.0; reader: lidl 0.1.0 (2043d8b)
"""Typed client for the ``mini_module`` module (LIDL contract 0.1.0).

A small contract for the multi-module golden.

Clients: :class:`AsyncMiniModuleClient` (asyncio, on a connected
:class:`logos_bridge.AsyncBridgeClient`) and :class:`MiniModuleClient` (blocking, on a
:class:`logos_bridge.BridgeClient`). Every call goes through ``rpc.call``.
Run ``check_compat()`` after connecting, and again after a subscription ends
with ``provider_changed``.
"""

from __future__ import annotations

import builtins as _builtins
import dataclasses as _dataclasses
import typing as _typing
from collections import abc as _abc

from logos_bridge import typed as _t
from logos_bridge.client import AsyncBridgeClient as _AsyncBridgeClient
from logos_bridge.compat import CompatReport as _CompatReport
from logos_bridge.models import Event as _Event
from logos_bridge.portal import BlockingPortal as _BlockingPortal
from logos_bridge.sync import BridgeClient as _BridgeClient

_t.require_codegen_format(1)

MODULE_NAME: _typing.Final = "mini_module"
INTERFACE_SHA256: _typing.Final = "589b01b9cbf84ab916d6d804868780c7c0e5d92063ee3b60061a55f330ff42ca"
CONTRACT_SHA256: _typing.Final[str | None] = (
    "68bde1680866ea0e450ed711e334e8c70013110eddb8889887cba029232e1f7c"
)
SHAPE_SHA256: _typing.Final = "14ae748c17d28fc9a8b1e741476849284cc38d75ba88c90c23a95c7c453bc8c0"

# The contract's shape (see logos_bridge.lidl.Interface.shape), checked at import.
INTERFACE: _typing.Final[_abc.Mapping[str, _typing.Any]] = {
    "shape": 1,
    "module": "mini_module",
    "records": {"Note": {"id": "tstr", "body": "bstr", "title": "?tstr", "tag": "?tstr"}},
    "methods": {
        "put": {"params": [["note", "Note"]], "returns": "Note"},
        "find": {"params": [["id", "tstr"], ["prefix", "?tstr"]], "returns": "result"},
        "clear": {"params": [], "returns": None},
        "name": {"params": [], "returns": "tstr"},
        "version": {"params": [], "returns": "tstr"},
        "lidl": {"params": [], "returns": "tstr"},
    },
    "events": {"added": [["note", "Note"]]},
}


@_dataclasses.dataclass(frozen=True, slots=True, kw_only=True)
class Note:
    """LIDL record ``Note``.

    Attributes:
        id: ``id: tstr``
        body: ``body: bstr``
        title: ``? title: tstr`` (optional; omitted from the wire when ``None``)
        tag: ``tag: ? tstr`` (optional; omitted from the wire when ``None``)
    """

    id: str = _dataclasses.field(metadata={"lidl": "id"})
    body: bytes = _dataclasses.field(metadata={"lidl": "body"})
    title: str | None = _dataclasses.field(default=None, metadata={"lidl": "title"})
    tag: str | None = _dataclasses.field(default=None, metadata={"lidl": "tag"})


@_dataclasses.dataclass(frozen=True, slots=True, kw_only=True)
class AddedEvent:
    """The ``added`` event: Emitted after put() stores a note.

    LIDL: ``event added(note: Note)``

    Attributes:
        note: ``Note``
        meta: the raw event (subscription, generation, ts, data).
    """

    note: Note = _dataclasses.field(metadata={"lidl": "note"})
    meta: _Event


MiniModuleEvent: _typing.TypeAlias = AddedEvent
MiniModuleEventName: _typing.TypeAlias = _typing.Literal["added"]
EVENT_NAMES: _typing.Final[tuple[MiniModuleEventName, ...]] = ("added",)
RECORD_TYPES: _typing.Final[_abc.Mapping[str, type]] = {"Note": Note}
EVENT_TYPES: _typing.Final[_abc.Mapping[str, type]] = {"added": AddedEvent}

_BINDING: _typing.Final = _t.Binding(
    INTERFACE, SHAPE_SHA256, INTERFACE_SHA256, records=RECORD_TYPES, events=EVENT_TYPES
)


class AsyncMiniModuleClient:
    """``mini_module`` over an :class:`logos_bridge.AsyncBridgeClient`.

    ``module`` is the bridge module name to call (default ``mini_module``).
    """

    def __init__(self, bridge: _AsyncBridgeClient, module: str = MODULE_NAME) -> None:
        self._bridge = bridge
        self._module = module

    def __repr__(self) -> str:
        return f"<AsyncMiniModuleClient {self._module} on {self._bridge.url}>"

    @property
    def bridge(self) -> _AsyncBridgeClient:
        return self._bridge

    @property
    def module(self) -> str:
        return self._module

    async def put(self, note: Note, *, timeout: float | None = None) -> Note:
        """Store a note and return it as stored.

        ::

            {"id": "n1", "body": {"_bytes": "aGk"}}

        LIDL: ``method put(note: Note) -> Note``

        Args:
            note: ``Note``.
            timeout: seconds to wait for the answer (default: the bridge client's).

        Returns:
            ``Note``.

        Raises:
            ArgumentError: an argument does not match the contract (nothing is sent).
            ProviderRejection: the provider refused the call.
            ResultDecodeError: the result does not match the contract.
            MethodNotFound: this bridge does not expose the method.
        """
        result = await _BINDING.call(self._bridge, self._module, "put", (note,), timeout)
        return _typing.cast("Note", result)

    async def find(
        self,
        id: str,
        prefix: str | None = None,
        *,
        timeout: float | None = None,
    ) -> _t.LogosResult[_typing.Any]:
        """Look a note up. An unknown id is success=false, not an error.

        LIDL: ``method find(id: tstr, prefix: ? tstr) -> result``

        Args:
            id: ``tstr``.
            prefix: ``? tstr`` (optional).
            timeout: seconds to wait for the answer (default: the bridge client's).

        Returns:
            The ``result``. ``success=False`` is an answer, not an exception;
            :meth:`LogosResult.unwrap` turns it into one.

        Raises:
            ArgumentError: an argument does not match the contract (nothing is sent).
            ProviderRejection: the provider refused the call.
            ResultDecodeError: the result does not match the contract.
            MethodNotFound: this bridge does not expose the method.
        """
        result = await _BINDING.call(self._bridge, self._module, "find", (id, prefix), timeout)
        return _typing.cast("_t.LogosResult[_typing.Any]", result)

    async def clear(self, *, timeout: float | None = None) -> None:
        """Forget every note.

        LIDL: ``method clear()``

        Args:
            timeout: seconds to wait for the answer (default: the bridge client's).

        Returns:
            Nothing: the method has no return value (the provider answers ``true``).

        Raises:
            ArgumentError: an argument does not match the contract (nothing is sent).
            ProviderRejection: the provider refused the call.
            ResultDecodeError: the result does not match the contract.
            MethodNotFound: this bridge does not expose the method.
        """
        await _BINDING.call(self._bridge, self._module, "clear", (), timeout)

    async def name(self, *, timeout: float | None = None) -> str:
        """The module's name, as declared in its metadata.

        LIDL: ``method name() -> tstr`` (derived built-in)

        Args:
            timeout: seconds to wait for the answer (default: the bridge client's).

        Returns:
            ``tstr``.

        Raises:
            ArgumentError: an argument does not match the contract (nothing is sent).
            ProviderRejection: the provider refused the call.
            ResultDecodeError: the result does not match the contract.
            MethodNotFound: this bridge does not expose the method.
        """
        result = await _BINDING.call(self._bridge, self._module, "name", (), timeout)
        return _typing.cast("str", result)

    async def version(self, *, timeout: float | None = None) -> str:
        """The module's version, as declared in its metadata.

        LIDL: ``method version() -> tstr`` (derived built-in)

        Args:
            timeout: seconds to wait for the answer (default: the bridge client's).

        Returns:
            ``tstr``.

        Raises:
            ArgumentError: an argument does not match the contract (nothing is sent).
            ProviderRejection: the provider refused the call.
            ResultDecodeError: the result does not match the contract.
            MethodNotFound: this bridge does not expose the method.
        """
        result = await _BINDING.call(self._bridge, self._module, "version", (), timeout)
        return _typing.cast("str", result)

    async def lidl(self, *, timeout: float | None = None) -> str:
        """The module's canonical LIDL interface document.

        LIDL: ``method lidl() -> tstr`` (derived built-in)

        Args:
            timeout: seconds to wait for the answer (default: the bridge client's).

        Returns:
            ``tstr``.

        Raises:
            ArgumentError: an argument does not match the contract (nothing is sent).
            ProviderRejection: the provider refused the call.
            ResultDecodeError: the result does not match the contract.
            MethodNotFound: this bridge does not expose the method.
        """
        result = await _BINDING.call(self._bridge, self._module, "lidl", (), timeout)
        return _typing.cast("str", result)

    def on_added(
        self,
        *,
        timeout: float | None = None,
        max_pending: int | None = None,
    ) -> _t.TypedSubscribeRequest[AddedEvent]:
        """Subscribe to ``added``: ``await`` it, or use ``async with``.

        Items are :class:`AddedEvent`; one that does not match the contract raises
        :class:`logos_bridge.EventDecodeError` (``results()`` yields it instead).
        """
        return _BINDING.subscribe(self._bridge, self._module, ("added",), timeout, max_pending)

    def decode_added(self, event: _Event) -> AddedEvent:
        """Decode a raw ``added`` event (``EventDecodeError`` if it does not match)."""
        decoded = _BINDING.decode_event("added", event)
        return _typing.cast("AddedEvent", decoded)

    def events(
        self,
        *names: MiniModuleEventName,
        timeout: float | None = None,
        max_pending: int | None = None,
    ) -> _t.TypedSubscribeRequest[MiniModuleEvent]:
        """One ordered stream of the named events (every event when none are named)."""
        return _BINDING.subscribe(self._bridge, self._module, names, timeout, max_pending)

    async def check_compat(
        self,
        *,
        allow_untyped: bool = False,
        discovery_wait: float | None = 10.0,
    ) -> _CompatReport:
        """Compare the served contract with this client's (exact, shape, structural, or names).

        Waits out ``pending``; raises :class:`logos_bridge.IncompatibleModule` (or
        :class:`logos_bridge.UntypedModule` without ``allow_untyped``) when no level applies.
        Use ``report.require(methods=..., events=...)`` for the members you need.
        """
        return await _BINDING.check_compat(
            self._bridge, self._module, allow_untyped=allow_untyped, discovery_wait=discovery_wait
        )


class MiniModuleClient:
    """The blocking twin of :class:`AsyncMiniModuleClient`, over a :class:`logos_bridge.BridgeClient`."""

    def __init__(self, bridge: _BridgeClient, module: str = MODULE_NAME) -> None:
        self._bridge = bridge
        self._portal = bridge.portal
        self._aio = AsyncMiniModuleClient(bridge.aio, module)

    def __repr__(self) -> str:
        return f"<MiniModuleClient {self._aio.module} on {self._bridge.url}>"

    @property
    def aio(self) -> AsyncMiniModuleClient:
        return self._aio

    @property
    def bridge(self) -> _BridgeClient:
        return self._bridge

    @property
    def module(self) -> str:
        return self._aio.module

    @property
    def portal(self) -> _BlockingPortal:
        return self._portal

    def put(self, note: Note, *, timeout: float | None = None) -> Note:
        """Store a note and return it as stored.

        ::

            {"id": "n1", "body": {"_bytes": "aGk"}}

        LIDL: ``method put(note: Note) -> Note``

        Args:
            note: ``Note``.
            timeout: seconds to wait for the answer (default: the bridge client's).

        Returns:
            ``Note``.

        Raises:
            ArgumentError: an argument does not match the contract (nothing is sent).
            ProviderRejection: the provider refused the call.
            ResultDecodeError: the result does not match the contract.
            MethodNotFound: this bridge does not expose the method.
        """
        return self._portal.call(self._aio.put, note, timeout=timeout)

    def find(
        self,
        id: str,
        prefix: str | None = None,
        *,
        timeout: float | None = None,
    ) -> _t.LogosResult[_typing.Any]:
        """Look a note up. An unknown id is success=false, not an error.

        LIDL: ``method find(id: tstr, prefix: ? tstr) -> result``

        Args:
            id: ``tstr``.
            prefix: ``? tstr`` (optional).
            timeout: seconds to wait for the answer (default: the bridge client's).

        Returns:
            The ``result``. ``success=False`` is an answer, not an exception;
            :meth:`LogosResult.unwrap` turns it into one.

        Raises:
            ArgumentError: an argument does not match the contract (nothing is sent).
            ProviderRejection: the provider refused the call.
            ResultDecodeError: the result does not match the contract.
            MethodNotFound: this bridge does not expose the method.
        """
        return self._portal.call(self._aio.find, id, prefix, timeout=timeout)

    def clear(self, *, timeout: float | None = None) -> None:
        """Forget every note.

        LIDL: ``method clear()``

        Args:
            timeout: seconds to wait for the answer (default: the bridge client's).

        Returns:
            Nothing: the method has no return value (the provider answers ``true``).

        Raises:
            ArgumentError: an argument does not match the contract (nothing is sent).
            ProviderRejection: the provider refused the call.
            ResultDecodeError: the result does not match the contract.
            MethodNotFound: this bridge does not expose the method.
        """
        self._portal.call(self._aio.clear, timeout=timeout)

    def name(self, *, timeout: float | None = None) -> str:
        """The module's name, as declared in its metadata.

        LIDL: ``method name() -> tstr`` (derived built-in)

        Args:
            timeout: seconds to wait for the answer (default: the bridge client's).

        Returns:
            ``tstr``.

        Raises:
            ArgumentError: an argument does not match the contract (nothing is sent).
            ProviderRejection: the provider refused the call.
            ResultDecodeError: the result does not match the contract.
            MethodNotFound: this bridge does not expose the method.
        """
        return self._portal.call(self._aio.name, timeout=timeout)

    def version(self, *, timeout: float | None = None) -> str:
        """The module's version, as declared in its metadata.

        LIDL: ``method version() -> tstr`` (derived built-in)

        Args:
            timeout: seconds to wait for the answer (default: the bridge client's).

        Returns:
            ``tstr``.

        Raises:
            ArgumentError: an argument does not match the contract (nothing is sent).
            ProviderRejection: the provider refused the call.
            ResultDecodeError: the result does not match the contract.
            MethodNotFound: this bridge does not expose the method.
        """
        return self._portal.call(self._aio.version, timeout=timeout)

    def lidl(self, *, timeout: float | None = None) -> str:
        """The module's canonical LIDL interface document.

        LIDL: ``method lidl() -> tstr`` (derived built-in)

        Args:
            timeout: seconds to wait for the answer (default: the bridge client's).

        Returns:
            ``tstr``.

        Raises:
            ArgumentError: an argument does not match the contract (nothing is sent).
            ProviderRejection: the provider refused the call.
            ResultDecodeError: the result does not match the contract.
            MethodNotFound: this bridge does not expose the method.
        """
        return self._portal.call(self._aio.lidl, timeout=timeout)

    def on_added(
        self,
        *,
        timeout: float | None = None,
        max_pending: int | None = None,
    ) -> _t.BlockingTypedSubscription[AddedEvent]:
        """Subscribe to ``added``; iterate the result, and close it (or use ``with``)."""
        request = self._aio.on_added(timeout=timeout, max_pending=max_pending)
        return _t.BlockingTypedSubscription.open(request, self._portal)

    def decode_added(self, event: _Event) -> AddedEvent:
        """Decode a raw ``added`` event."""
        return self._aio.decode_added(event)

    def events(
        self,
        *names: MiniModuleEventName,
        timeout: float | None = None,
        max_pending: int | None = None,
    ) -> _t.BlockingTypedSubscription[MiniModuleEvent]:
        """One ordered, blocking stream of the named events (every event when none are named)."""
        request = self._aio.events(*names, timeout=timeout, max_pending=max_pending)
        return _t.BlockingTypedSubscription.open(request, self._portal)

    def check_compat(
        self,
        *,
        allow_untyped: bool = False,
        discovery_wait: float | None = 10.0,
    ) -> _CompatReport:
        """Blocking :meth:`AsyncMiniModuleClient.check_compat`."""
        return self._portal.call(
            self._aio.check_compat, allow_untyped=allow_untyped, discovery_wait=discovery_wait
        )
