# GENERATED by logos-bridge-codegen. Do not edit: regenerate instead.
# Contract: test_fullapi_cpp 1.0.0
# INTERFACE_SHA256: 2f5db9ac25ff9bb96149f8a2f7f3f89d854c6d1f82d67c5a969b007dea6ff6c7
# CONTRACT_SHA256: 6e92054db23a3b3bfb78179647a0d67315c48a2efd6e0a515b5f0b9bf6b7687c
# SHAPE_SHA256: 38b01e042e6d1eb2f0efcc3f5efd6909a16c0436263c8064269d36fdb8160f20
# Codegen format: 1
# Regenerate: nix run .#regen-goldens
# Source: lidl tests/fixtures/lidl/test_fullapi_cpp.lidl
# Generator: logos-bridge 0.1.0; reader: lidl 0.1.0 (2043d8b)
"""Typed client for the ``test_fullapi_cpp`` module (LIDL contract 1.0.0).

Universal C++ provider exercising every supported method parameter type, return type, and event
parameter type. Reference implementation of the full_api contract; mirrored 1:1 by the Rust provider
test_fullapi_rust so the same interface can be bound to either.

Clients: :class:`AsyncTestFullapiCppClient` (asyncio, on a connected
:class:`logos_bridge.AsyncBridgeClient`) and :class:`TestFullapiCppClient` (blocking, on a
:class:`logos_bridge.BridgeClient`). Every call goes through ``rpc.call``.
Run ``check_compat()`` after connecting, and again after a subscription ends
with ``provider_changed``.
"""

from __future__ import annotations

import builtins as _builtins
import dataclasses as _dataclasses
import typing as _typing
from collections import abc as _abc

from logos_bridge import typed as _t
from logos_bridge.client import AsyncBridgeClient as _AsyncBridgeClient
from logos_bridge.compat import CompatReport as _CompatReport
from logos_bridge.models import Event as _Event
from logos_bridge.portal import BlockingPortal as _BlockingPortal
from logos_bridge.sync import BridgeClient as _BridgeClient

_t.require_codegen_format(1)

MODULE_NAME: _typing.Final = "test_fullapi_cpp"
INTERFACE_SHA256: _typing.Final = "2f5db9ac25ff9bb96149f8a2f7f3f89d854c6d1f82d67c5a969b007dea6ff6c7"
CONTRACT_SHA256: _typing.Final[str | None] = (
    "6e92054db23a3b3bfb78179647a0d67315c48a2efd6e0a515b5f0b9bf6b7687c"
)
SHAPE_SHA256: _typing.Final = "38b01e042e6d1eb2f0efcc3f5efd6909a16c0436263c8064269d36fdb8160f20"

# The contract's shape (see logos_bridge.lidl.Interface.shape), checked at import.
INTERFACE: _typing.Final[_abc.Mapping[str, _typing.Any]] = {
    "shape": 1,
    "module": "test_fullapi_cpp",
    "records": {},
    "methods": {
        "whoAmI": {"params": [], "returns": "tstr"},
        "echoString": {"params": [["v", "tstr"]], "returns": "tstr"},
        "echoBytes": {"params": [["v", "bstr"]], "returns": "bstr"},
        "echoInt": {"params": [["v", "int"]], "returns": "int"},
        "echoUint": {"params": [["v", "uint"]], "returns": "uint"},
        "echoDouble": {"params": [["v", "float64"]], "returns": "float64"},
        "echoBool": {"params": [["v", "bool"]], "returns": "bool"},
        "echoAny": {"params": [["v", "any"]], "returns": "any"},
        "echoStringList": {"params": [["v", "[tstr]"]], "returns": "[tstr]"},
        "echoIntList": {"params": [["v", "[int]"]], "returns": "[int]"},
        "echoUintList": {"params": [["v", "[uint]"]], "returns": "[uint]"},
        "echoDoubleList": {"params": [["v", "[float64]"]], "returns": "[float64]"},
        "echoBoolList": {"params": [["v", "[bool]"]], "returns": "[bool]"},
        "echoList": {"params": [["v", "[any]"]], "returns": "[any]"},
        "echoMap": {"params": [["v", "{tstr:any}"]], "returns": "{tstr:any}"},
        "echoTriple": {"params": [["i", "int"], ["s", "tstr"], ["b", "bstr"]], "returns": "tstr"},
        "doVoid": {"params": [], "returns": None},
        "makeResult": {"params": [["ok", "bool"]], "returns": "result"},
        "fireStringEvent": {"params": [["v", "tstr"]], "returns": "bool"},
        "fireBytesEvent": {"params": [["v", "bstr"]], "returns": "bool"},
        "fireIntEvent": {"params": [["v", "int"]], "returns": "bool"},
        "fireUintEvent": {"params": [["v", "uint"]], "returns": "bool"},
        "fireDoubleEvent": {"params": [["v", "float64"]], "returns": "bool"},
        "fireBoolEvent": {"params": [["v", "bool"]], "returns": "bool"},
        "fireAnyEvent": {"params": [["v", "any"]], "returns": "bool"},
        "fireStringListEvent": {"params": [["v", "[tstr]"]], "returns": "bool"},
        "fireIntListEvent": {"params": [["v", "[int]"]], "returns": "bool"},
        "fireUintListEvent": {"params": [["v", "[uint]"]], "returns": "bool"},
        "fireDoubleListEvent": {"params": [["v", "[float64]"]], "returns": "bool"},
        "fireBoolListEvent": {"params": [["v", "[bool]"]], "returns": "bool"},
        "fireListEvent": {"params": [["v", "[any]"]], "returns": "bool"},
        "fireMapEvent": {"params": [["v", "{tstr:any}"]], "returns": "bool"},
        "fireTripleEvent": {"params": [["i", "int"], ["s", "tstr"], ["b", "bstr"]], "returns": "bool"},
        "name": {"params": [], "returns": "tstr"},
        "version": {"params": [], "returns": "tstr"},
        "lidl": {"params": [], "returns": "tstr"},
    },
    "events": {
        "stringEvent": [["v", "tstr"]],
        "bytesEvent": [["v", "bstr"]],
        "intEvent": [["v", "int"]],
        "uintEvent": [["v", "uint"]],
        "doubleEvent": [["v", "float64"]],
        "boolEvent": [["v", "bool"]],
        "anyEvent": [["v", "any"]],
        "stringListEvent": [["v", "[tstr]"]],
        "intListEvent": [["v", "[int]"]],
        "uintListEvent": [["v", "[uint]"]],
        "doubleListEvent": [["v", "[float64]"]],
        "boolListEvent": [["v", "[bool]"]],
        "listEvent": [["v", "[any]"]],
        "mapEvent": [["v", "{tstr:any}"]],
        "tripleEvent": [["i", "int"], ["s", "tstr"], ["b", "bstr"]],
    },
}


@_dataclasses.dataclass(frozen=True, slots=True, kw_only=True)
class StringEventEvent:
    """The ``stringEvent`` event.

    LIDL: ``event stringEvent(v: tstr)``

    Attributes:
        v: ``tstr``
        meta: the raw event (subscription, generation, ts, data).
    """

    v: str = _dataclasses.field(metadata={"lidl": "v"})
    meta: _Event


@_dataclasses.dataclass(frozen=True, slots=True, kw_only=True)
class BytesEventEvent:
    """The ``bytesEvent`` event.

    LIDL: ``event bytesEvent(v: bstr)``

    Attributes:
        v: ``bstr``
        meta: the raw event (subscription, generation, ts, data).
    """

    v: bytes = _dataclasses.field(metadata={"lidl": "v"})
    meta: _Event


@_dataclasses.dataclass(frozen=True, slots=True, kw_only=True)
class IntEventEvent:
    """The ``intEvent`` event.

    LIDL: ``event intEvent(v: int)``

    Attributes:
        v: ``int``
        meta: the raw event (subscription, generation, ts, data).
    """

    v: int = _dataclasses.field(metadata={"lidl": "v"})
    meta: _Event


@_dataclasses.dataclass(frozen=True, slots=True, kw_only=True)
class UintEventEvent:
    """The ``uintEvent`` event.

    LIDL: ``event uintEvent(v: uint)``

    Attributes:
        v: ``uint``
        meta: the raw event (subscription, generation, ts, data).
    """

    v: int = _dataclasses.field(metadata={"lidl": "v"})
    meta: _Event


@_dataclasses.dataclass(frozen=True, slots=True, kw_only=True)
class DoubleEventEvent:
    """The ``doubleEvent`` event.

    LIDL: ``event doubleEvent(v: float64)``

    Attributes:
        v: ``float64``
        meta: the raw event (subscription, generation, ts, data).
    """

    v: float = _dataclasses.field(metadata={"lidl": "v"})
    meta: _Event


@_dataclasses.dataclass(frozen=True, slots=True, kw_only=True)
class BoolEventEvent:
    """The ``boolEvent`` event.

    LIDL: ``event boolEvent(v: bool)``

    Attributes:
        v: ``bool``
        meta: the raw event (subscription, generation, ts, data).
    """

    v: bool = _dataclasses.field(metadata={"lidl": "v"})
    meta: _Event


@_dataclasses.dataclass(frozen=True, slots=True, kw_only=True)
class AnyEventEvent:
    """The ``anyEvent`` event.

    LIDL: ``event anyEvent(v: any)``

    Attributes:
        v: ``any``
        meta: the raw event (subscription, generation, ts, data).
    """

    v: _typing.Any = _dataclasses.field(metadata={"lidl": "v"})
    meta: _Event


@_dataclasses.dataclass(frozen=True, slots=True, kw_only=True)
class StringListEventEvent:
    """The ``stringListEvent`` event.

    LIDL: ``event stringListEvent(v: [tstr])``

    Attributes:
        v: ``[tstr]``
        meta: the raw event (subscription, generation, ts, data).
    """

    v: list[str] = _dataclasses.field(metadata={"lidl": "v"})
    meta: _Event


@_dataclasses.dataclass(frozen=True, slots=True, kw_only=True)
class IntListEventEvent:
    """The ``intListEvent`` event.

    LIDL: ``event intListEvent(v: [int])``

    Attributes:
        v: ``[int]``
        meta: the raw event (subscription, generation, ts, data).
    """

    v: list[int] = _dataclasses.field(metadata={"lidl": "v"})
    meta: _Event


@_dataclasses.dataclass(frozen=True, slots=True, kw_only=True)
class UintListEventEvent:
    """The ``uintListEvent`` event.

    LIDL: ``event uintListEvent(v: [uint])``

    Attributes:
        v: ``[uint]``
        meta: the raw event (subscription, generation, ts, data).
    """

    v: list[int] = _dataclasses.field(metadata={"lidl": "v"})
    meta: _Event


@_dataclasses.dataclass(frozen=True, slots=True, kw_only=True)
class DoubleListEventEvent:
    """The ``doubleListEvent`` event.

    LIDL: ``event doubleListEvent(v: [float64])``

    Attributes:
        v: ``[float64]``
        meta: the raw event (subscription, generation, ts, data).
    """

    v: list[float] = _dataclasses.field(metadata={"lidl": "v"})
    meta: _Event


@_dataclasses.dataclass(frozen=True, slots=True, kw_only=True)
class BoolListEventEvent:
    """The ``boolListEvent`` event.

    LIDL: ``event boolListEvent(v: [bool])``

    Attributes:
        v: ``[bool]``
        meta: the raw event (subscription, generation, ts, data).
    """

    v: list[bool] = _dataclasses.field(metadata={"lidl": "v"})
    meta: _Event


@_dataclasses.dataclass(frozen=True, slots=True, kw_only=True)
class ListEventEvent:
    """The ``listEvent`` event.

    LIDL: ``event listEvent(v: [any])``

    Attributes:
        v: ``[any]``
        meta: the raw event (subscription, generation, ts, data).
    """

    v: list[_typing.Any] = _dataclasses.field(metadata={"lidl": "v"})
    meta: _Event


@_dataclasses.dataclass(frozen=True, slots=True, kw_only=True)
class MapEventEvent:
    """The ``mapEvent`` event.

    LIDL: ``event mapEvent(v: {tstr: any})``

    Attributes:
        v: ``{tstr: any}``
        meta: the raw event (subscription, generation, ts, data).
    """

    v: dict[str, _typing.Any] = _dataclasses.field(metadata={"lidl": "v"})
    meta: _Event


@_dataclasses.dataclass(frozen=True, slots=True, kw_only=True)
class TripleEventEvent:
    """The ``tripleEvent`` event.

    LIDL: ``event tripleEvent(i: int, s: tstr, b: bstr)``

    Attributes:
        i: ``int``
        s: ``tstr``
        b: ``bstr``
        meta: the raw event (subscription, generation, ts, data).
    """

    i: int = _dataclasses.field(metadata={"lidl": "i"})
    s: str = _dataclasses.field(metadata={"lidl": "s"})
    b: bytes = _dataclasses.field(metadata={"lidl": "b"})
    meta: _Event


TestFullapiCppEvent: _typing.TypeAlias = _typing.Union[
    StringEventEvent,
    BytesEventEvent,
    IntEventEvent,
    UintEventEvent,
    DoubleEventEvent,
    BoolEventEvent,
    AnyEventEvent,
    StringListEventEvent,
    IntListEventEvent,
    UintListEventEvent,
    DoubleListEventEvent,
    BoolListEventEvent,
    ListEventEvent,
    MapEventEvent,
    TripleEventEvent,
]
TestFullapiCppEventName: _typing.TypeAlias = _typing.Literal[
    "stringEvent",
    "bytesEvent",
    "intEvent",
    "uintEvent",
    "doubleEvent",
    "boolEvent",
    "anyEvent",
    "stringListEvent",
    "intListEvent",
    "uintListEvent",
    "doubleListEvent",
    "boolListEvent",
    "listEvent",
    "mapEvent",
    "tripleEvent",
]
EVENT_NAMES: _typing.Final[tuple[TestFullapiCppEventName, ...]] = (
    "stringEvent",
    "bytesEvent",
    "intEvent",
    "uintEvent",
    "doubleEvent",
    "boolEvent",
    "anyEvent",
    "stringListEvent",
    "intListEvent",
    "uintListEvent",
    "doubleListEvent",
    "boolListEvent",
    "listEvent",
    "mapEvent",
    "tripleEvent",
)
RECORD_TYPES: _typing.Final[_abc.Mapping[str, type]] = {}
EVENT_TYPES: _typing.Final[_abc.Mapping[str, type]] = {
    "stringEvent": StringEventEvent,
    "bytesEvent": BytesEventEvent,
    "intEvent": IntEventEvent,
    "uintEvent": UintEventEvent,
    "doubleEvent": DoubleEventEvent,
    "boolEvent": BoolEventEvent,
    "anyEvent": AnyEventEvent,
    "stringListEvent": StringListEventEvent,
    "intListEvent": IntListEventEvent,
    "uintListEvent": UintListEventEvent,
    "doubleListEvent": DoubleListEventEvent,
    "boolListEvent": BoolListEventEvent,
    "listEvent": ListEventEvent,
    "mapEvent": MapEventEvent,
    "tripleEvent": TripleEventEvent,
}

_BINDING: _typing.Final = _t.Binding(
    INTERFACE, SHAPE_SHA256, INTERFACE_SHA256, records=RECORD_TYPES, events=EVENT_TYPES
)


class AsyncTestFullapiCppClient:
    """``test_fullapi_cpp`` over an :class:`logos_bridge.AsyncBridgeClient`.

    ``module`` is the bridge module name to call (default ``test_fullapi_cpp``).
    """

    def __init__(self, bridge: _AsyncBridgeClient, module: str = MODULE_NAME) -> None:
        self._bridge = bridge
        self._module = module

    def __repr__(self) -> str:
        return f"<AsyncTestFullapiCppClient {self._module} on {self._bridge.url}>"

    @property
    def bridge(self) -> _AsyncBridgeClient:
        return self._bridge

    @property
    def module(self) -> str:
        return self._module

    async def who_am_i(self, *, timeout: float | None = None) -> str:
        """Call ``test_fullapi_cpp.whoAmI``.

        LIDL: ``method whoAmI() -> tstr``

        Args:
            timeout: seconds to wait for the answer (default: the bridge client's).

        Returns:
            ``tstr``.

        Raises:
            ArgumentError: an argument does not match the contract (nothing is sent).
            ProviderRejection: the provider refused the call.
            ResultDecodeError: the result does not match the contract.
            MethodNotFound: this bridge does not expose the method.
        """
        result = await _BINDING.call(self._bridge, self._module, "whoAmI", (), timeout)
        return _typing.cast("str", result)

    async def echo_string(self, v: str, *, timeout: float | None = None) -> str:
        """Call ``test_fullapi_cpp.echoString``.

        LIDL: ``method echoString(v: tstr) -> tstr``

        Args:
            v: ``tstr``.
            timeout: seconds to wait for the answer (default: the bridge client's).

        Returns:
            ``tstr``.

        Raises:
            ArgumentError: an argument does not match the contract (nothing is sent).
            ProviderRejection: the provider refused the call.
            ResultDecodeError: the result does not match the contract.
            MethodNotFound: this bridge does not expose the method.
        """
        result = await _BINDING.call(self._bridge, self._module, "echoString", (v,), timeout)
        return _typing.cast("str", result)

    async def echo_bytes(self, v: bytes, *, timeout: float | None = None) -> bytes:
        """Call ``test_fullapi_cpp.echoBytes``.

        LIDL: ``method echoBytes(v: bstr) -> bstr``

        Args:
            v: ``bstr``.
            timeout: seconds to wait for the answer (default: the bridge client's).

        Returns:
            ``bstr``.

        Raises:
            ArgumentError: an argument does not match the contract (nothing is sent).
            ProviderRejection: the provider refused the call.
            ResultDecodeError: the result does not match the contract.
            MethodNotFound: this bridge does not expose the method.
        """
        result = await _BINDING.call(self._bridge, self._module, "echoBytes", (v,), timeout)
        return _typing.cast("bytes", result)

    async def echo_int(self, v: int, *, timeout: float | None = None) -> int:
        """Call ``test_fullapi_cpp.echoInt``.

        LIDL: ``method echoInt(v: int) -> int``

        Args:
            v: ``int``.
            timeout: seconds to wait for the answer (default: the bridge client's).

        Returns:
            ``int``.

        Raises:
            ArgumentError: an argument does not match the contract (nothing is sent).
            ProviderRejection: the provider refused the call.
            ResultDecodeError: the result does not match the contract.
            MethodNotFound: this bridge does not expose the method.
        """
        result = await _BINDING.call(self._bridge, self._module, "echoInt", (v,), timeout)
        return _typing.cast("int", result)

    async def echo_uint(self, v: int, *, timeout: float | None = None) -> int:
        """Call ``test_fullapi_cpp.echoUint``.

        LIDL: ``method echoUint(v: uint) -> uint``

        Args:
            v: ``uint``.
            timeout: seconds to wait for the answer (default: the bridge client's).

        Returns:
            ``uint``.

        Raises:
            ArgumentError: an argument does not match the contract (nothing is sent).
            ProviderRejection: the provider refused the call.
            ResultDecodeError: the result does not match the contract.
            MethodNotFound: this bridge does not expose the method.
        """
        result = await _BINDING.call(self._bridge, self._module, "echoUint", (v,), timeout)
        return _typing.cast("int", result)

    async def echo_double(self, v: float, *, timeout: float | None = None) -> float:
        """Call ``test_fullapi_cpp.echoDouble``.

        LIDL: ``method echoDouble(v: float64) -> float64``

        Args:
            v: ``float64``.
            timeout: seconds to wait for the answer (default: the bridge client's).

        Returns:
            ``float64``.

        Raises:
            ArgumentError: an argument does not match the contract (nothing is sent).
            ProviderRejection: the provider refused the call.
            ResultDecodeError: the result does not match the contract.
            MethodNotFound: this bridge does not expose the method.
        """
        result = await _BINDING.call(self._bridge, self._module, "echoDouble", (v,), timeout)
        return _typing.cast("float", result)

    async def echo_bool(self, v: bool, *, timeout: float | None = None) -> bool:
        """Call ``test_fullapi_cpp.echoBool``.

        LIDL: ``method echoBool(v: bool) -> bool``

        Args:
            v: ``bool``.
            timeout: seconds to wait for the answer (default: the bridge client's).

        Returns:
            ``bool``.

        Raises:
            ArgumentError: an argument does not match the contract (nothing is sent).
            ProviderRejection: the provider refused the call.
            ResultDecodeError: the result does not match the contract.
            MethodNotFound: this bridge does not expose the method.
        """
        result = await _BINDING.call(self._bridge, self._module, "echoBool", (v,), timeout)
        return _typing.cast("bool", result)

    async def echo_any(self, v: _typing.Any, *, timeout: float | None = None) -> _typing.Any:
        """Call ``test_fullapi_cpp.echoAny``.

        LIDL: ``method echoAny(v: any) -> any``

        Args:
            v: ``any``.
            timeout: seconds to wait for the answer (default: the bridge client's).

        Returns:
            ``any``.

        Raises:
            ArgumentError: an argument does not match the contract (nothing is sent).
            ProviderRejection: the provider refused the call.
                This return type can hold a value shaped like a refusal; such a value is
                reported as a rejection too.
            ResultDecodeError: the result does not match the contract.
            MethodNotFound: this bridge does not expose the method.
        """
        return await _BINDING.call(self._bridge, self._module, "echoAny", (v,), timeout)

    async def echo_string_list(self, v: _abc.Sequence[str], *, timeout: float | None = None) -> list[str]:
        """Call ``test_fullapi_cpp.echoStringList``.

        LIDL: ``method echoStringList(v: [tstr]) -> [tstr]``

        Args:
            v: ``[tstr]``.
            timeout: seconds to wait for the answer (default: the bridge client's).

        Returns:
            ``[tstr]``.

        Raises:
            ArgumentError: an argument does not match the contract (nothing is sent).
            ProviderRejection: the provider refused the call.
            ResultDecodeError: the result does not match the contract.
            MethodNotFound: this bridge does not expose the method.
        """
        result = await _BINDING.call(self._bridge, self._module, "echoStringList", (v,), timeout)
        return _typing.cast("list[str]", result)

    async def echo_int_list(self, v: _abc.Sequence[int], *, timeout: float | None = None) -> list[int]:
        """Call ``test_fullapi_cpp.echoIntList``.

        LIDL: ``method echoIntList(v: [int]) -> [int]``

        Args:
            v: ``[int]``.
            timeout: seconds to wait for the answer (default: the bridge client's).

        Returns:
            ``[int]``.

        Raises:
            ArgumentError: an argument does not match the contract (nothing is sent).
            ProviderRejection: the provider refused the call.
            ResultDecodeError: the result does not match the contract.
            MethodNotFound: this bridge does not expose the method.
        """
        result = await _BINDING.call(self._bridge, self._module, "echoIntList", (v,), timeout)
        return _typing.cast("list[int]", result)

    async def echo_uint_list(self, v: _abc.Sequence[int], *, timeout: float | None = None) -> list[int]:
        """Call ``test_fullapi_cpp.echoUintList``.

        LIDL: ``method echoUintList(v: [uint]) -> [uint]``

        Args:
            v: ``[uint]``.
            timeout: seconds to wait for the answer (default: the bridge client's).

        Returns:
            ``[uint]``.

        Raises:
            ArgumentError: an argument does not match the contract (nothing is sent).
            ProviderRejection: the provider refused the call.
            ResultDecodeError: the result does not match the contract.
            MethodNotFound: this bridge does not expose the method.
        """
        result = await _BINDING.call(self._bridge, self._module, "echoUintList", (v,), timeout)
        return _typing.cast("list[int]", result)

    async def echo_double_list(self, v: _abc.Sequence[float], *, timeout: float | None = None) -> list[float]:
        """Call ``test_fullapi_cpp.echoDoubleList``.

        LIDL: ``method echoDoubleList(v: [float64]) -> [float64]``

        Args:
            v: ``[float64]``.
            timeout: seconds to wait for the answer (default: the bridge client's).

        Returns:
            ``[float64]``.

        Raises:
            ArgumentError: an argument does not match the contract (nothing is sent).
            ProviderRejection: the provider refused the call.
            ResultDecodeError: the result does not match the contract.
            MethodNotFound: this bridge does not expose the method.
        """
        result = await _BINDING.call(self._bridge, self._module, "echoDoubleList", (v,), timeout)
        return _typing.cast("list[float]", result)

    async def echo_bool_list(self, v: _abc.Sequence[bool], *, timeout: float | None = None) -> list[bool]:
        """Call ``test_fullapi_cpp.echoBoolList``.

        LIDL: ``method echoBoolList(v: [bool]) -> [bool]``

        Args:
            v: ``[bool]``.
            timeout: seconds to wait for the answer (default: the bridge client's).

        Returns:
            ``[bool]``.

        Raises:
            ArgumentError: an argument does not match the contract (nothing is sent).
            ProviderRejection: the provider refused the call.
            ResultDecodeError: the result does not match the contract.
            MethodNotFound: this bridge does not expose the method.
        """
        result = await _BINDING.call(self._bridge, self._module, "echoBoolList", (v,), timeout)
        return _typing.cast("list[bool]", result)

    async def echo_list(
        self,
        v: _abc.Sequence[_typing.Any],
        *,
        timeout: float | None = None,
    ) -> list[_typing.Any]:
        """Call ``test_fullapi_cpp.echoList``.

        LIDL: ``method echoList(v: [any]) -> [any]``

        Args:
            v: ``[any]``.
            timeout: seconds to wait for the answer (default: the bridge client's).

        Returns:
            ``[any]``.

        Raises:
            ArgumentError: an argument does not match the contract (nothing is sent).
            ProviderRejection: the provider refused the call.
            ResultDecodeError: the result does not match the contract.
            MethodNotFound: this bridge does not expose the method.
        """
        result = await _BINDING.call(self._bridge, self._module, "echoList", (v,), timeout)
        return _typing.cast("list[_typing.Any]", result)

    async def echo_map(
        self,
        v: _abc.Mapping[str, _typing.Any],
        *,
        timeout: float | None = None,
    ) -> dict[str, _typing.Any]:
        """Call ``test_fullapi_cpp.echoMap``.

        LIDL: ``method echoMap(v: {tstr: any}) -> {tstr: any}``

        Args:
            v: ``{tstr: any}``.
            timeout: seconds to wait for the answer (default: the bridge client's).

        Returns:
            ``{tstr: any}``.

        Raises:
            ArgumentError: an argument does not match the contract (nothing is sent).
            ProviderRejection: the provider refused the call.
                This return type can hold a value shaped like a refusal; such a value is
                reported as a rejection too.
            ResultDecodeError: the result does not match the contract.
            MethodNotFound: this bridge does not expose the method.
        """
        result = await _BINDING.call(self._bridge, self._module, "echoMap", (v,), timeout)
        return _typing.cast("dict[str, _typing.Any]", result)

    async def echo_triple(self, i: int, s: str, b: bytes, *, timeout: float | None = None) -> str:
        """Call ``test_fullapi_cpp.echoTriple``.

        LIDL: ``method echoTriple(i: int, s: tstr, b: bstr) -> tstr``

        Args:
            i: ``int``.
            s: ``tstr``.
            b: ``bstr``.
            timeout: seconds to wait for the answer (default: the bridge client's).

        Returns:
            ``tstr``.

        Raises:
            ArgumentError: an argument does not match the contract (nothing is sent).
            ProviderRejection: the provider refused the call.
            ResultDecodeError: the result does not match the contract.
            MethodNotFound: this bridge does not expose the method.
        """
        result = await _BINDING.call(self._bridge, self._module, "echoTriple", (i, s, b), timeout)
        return _typing.cast("str", result)

    async def do_void(self, *, timeout: float | None = None) -> None:
        """Call ``test_fullapi_cpp.doVoid``.

        LIDL: ``method doVoid()``

        Args:
            timeout: seconds to wait for the answer (default: the bridge client's).

        Returns:
            Nothing: the method has no return value (the provider answers ``true``).

        Raises:
            ArgumentError: an argument does not match the contract (nothing is sent).
            ProviderRejection: the provider refused the call.
            ResultDecodeError: the result does not match the contract.
            MethodNotFound: this bridge does not expose the method.
        """
        await _BINDING.call(self._bridge, self._module, "doVoid", (), timeout)

    async def make_result(self, ok: bool, *, timeout: float | None = None) -> _t.LogosResult[_typing.Any]:
        """Call ``test_fullapi_cpp.makeResult``.

        LIDL: ``method makeResult(ok: bool) -> result``

        Args:
            ok: ``bool``.
            timeout: seconds to wait for the answer (default: the bridge client's).

        Returns:
            The ``result``. ``success=False`` is an answer, not an exception;
            :meth:`LogosResult.unwrap` turns it into one.

        Raises:
            ArgumentError: an argument does not match the contract (nothing is sent).
            ProviderRejection: the provider refused the call.
            ResultDecodeError: the result does not match the contract.
            MethodNotFound: this bridge does not expose the method.
        """
        result = await _BINDING.call(self._bridge, self._module, "makeResult", (ok,), timeout)
        return _typing.cast("_t.LogosResult[_typing.Any]", result)

    async def fire_string_event(self, v: str, *, timeout: float | None = None) -> bool:
        """Call ``test_fullapi_cpp.fireStringEvent``.

        LIDL: ``method fireStringEvent(v: tstr) -> bool``

        Args:
            v: ``tstr``.
            timeout: seconds to wait for the answer (default: the bridge client's).

        Returns:
            ``bool``.

        Raises:
            ArgumentError: an argument does not match the contract (nothing is sent).
            ProviderRejection: the provider refused the call.
            ResultDecodeError: the result does not match the contract.
            MethodNotFound: this bridge does not expose the method.
        """
        result = await _BINDING.call(self._bridge, self._module, "fireStringEvent", (v,), timeout)
        return _typing.cast("bool", result)

    async def fire_bytes_event(self, v: bytes, *, timeout: float | None = None) -> bool:
        """Call ``test_fullapi_cpp.fireBytesEvent``.

        LIDL: ``method fireBytesEvent(v: bstr) -> bool``

        Args:
            v: ``bstr``.
            timeout: seconds to wait for the answer (default: the bridge client's).

        Returns:
            ``bool``.

        Raises:
            ArgumentError: an argument does not match the contract (nothing is sent).
            ProviderRejection: the provider refused the call.
            ResultDecodeError: the result does not match the contract.
            MethodNotFound: this bridge does not expose the method.
        """
        result = await _BINDING.call(self._bridge, self._module, "fireBytesEvent", (v,), timeout)
        return _typing.cast("bool", result)

    async def fire_int_event(self, v: int, *, timeout: float | None = None) -> bool:
        """Call ``test_fullapi_cpp.fireIntEvent``.

        LIDL: ``method fireIntEvent(v: int) -> bool``

        Args:
            v: ``int``.
            timeout: seconds to wait for the answer (default: the bridge client's).

        Returns:
            ``bool``.

        Raises:
            ArgumentError: an argument does not match the contract (nothing is sent).
            ProviderRejection: the provider refused the call.
            ResultDecodeError: the result does not match the contract.
            MethodNotFound: this bridge does not expose the method.
        """
        result = await _BINDING.call(self._bridge, self._module, "fireIntEvent", (v,), timeout)
        return _typing.cast("bool", result)

    async def fire_uint_event(self, v: int, *, timeout: float | None = None) -> bool:
        """Call ``test_fullapi_cpp.fireUintEvent``.

        LIDL: ``method fireUintEvent(v: uint) -> bool``

        Args:
            v: ``uint``.
            timeout: seconds to wait for the answer (default: the bridge client's).

        Returns:
            ``bool``.

        Raises:
            ArgumentError: an argument does not match the contract (nothing is sent).
            ProviderRejection: the provider refused the call.
            ResultDecodeError: the result does not match the contract.
            MethodNotFound: this bridge does not expose the method.
        """
        result = await _BINDING.call(self._bridge, self._module, "fireUintEvent", (v,), timeout)
        return _typing.cast("bool", result)

    async def fire_double_event(self, v: float, *, timeout: float | None = None) -> bool:
        """Call ``test_fullapi_cpp.fireDoubleEvent``.

        LIDL: ``method fireDoubleEvent(v: float64) -> bool``

        Args:
            v: ``float64``.
            timeout: seconds to wait for the answer (default: the bridge client's).

        Returns:
            ``bool``.

        Raises:
            ArgumentError: an argument does not match the contract (nothing is sent).
            ProviderRejection: the provider refused the call.
            ResultDecodeError: the result does not match the contract.
            MethodNotFound: this bridge does not expose the method.
        """
        result = await _BINDING.call(self._bridge, self._module, "fireDoubleEvent", (v,), timeout)
        return _typing.cast("bool", result)

    async def fire_bool_event(self, v: bool, *, timeout: float | None = None) -> bool:
        """Call ``test_fullapi_cpp.fireBoolEvent``.

        LIDL: ``method fireBoolEvent(v: bool) -> bool``

        Args:
            v: ``bool``.
            timeout: seconds to wait for the answer (default: the bridge client's).

        Returns:
            ``bool``.

        Raises:
            ArgumentError: an argument does not match the contract (nothing is sent).
            ProviderRejection: the provider refused the call.
            ResultDecodeError: the result does not match the contract.
            MethodNotFound: this bridge does not expose the method.
        """
        result = await _BINDING.call(self._bridge, self._module, "fireBoolEvent", (v,), timeout)
        return _typing.cast("bool", result)

    async def fire_any_event(self, v: _typing.Any, *, timeout: float | None = None) -> bool:
        """Call ``test_fullapi_cpp.fireAnyEvent``.

        LIDL: ``method fireAnyEvent(v: any) -> bool``

        Args:
            v: ``any``.
            timeout: seconds to wait for the answer (default: the bridge client's).

        Returns:
            ``bool``.

        Raises:
            ArgumentError: an argument does not match the contract (nothing is sent).
            ProviderRejection: the provider refused the call.
            ResultDecodeError: the result does not match the contract.
            MethodNotFound: this bridge does not expose the method.
        """
        result = await _BINDING.call(self._bridge, self._module, "fireAnyEvent", (v,), timeout)
        return _typing.cast("bool", result)

    async def fire_string_list_event(self, v: _abc.Sequence[str], *, timeout: float | None = None) -> bool:
        """Call ``test_fullapi_cpp.fireStringListEvent``.

        LIDL: ``method fireStringListEvent(v: [tstr]) -> bool``

        Args:
            v: ``[tstr]``.
            timeout: seconds to wait for the answer (default: the bridge client's).

        Returns:
            ``bool``.

        Raises:
            ArgumentError: an argument does not match the contract (nothing is sent).
            ProviderRejection: the provider refused the call.
            ResultDecodeError: the result does not match the contract.
            MethodNotFound: this bridge does not expose the method.
        """
        result = await _BINDING.call(self._bridge, self._module, "fireStringListEvent", (v,), timeout)
        return _typing.cast("bool", result)

    async def fire_int_list_event(self, v: _abc.Sequence[int], *, timeout: float | None = None) -> bool:
        """Call ``test_fullapi_cpp.fireIntListEvent``.

        LIDL: ``method fireIntListEvent(v: [int]) -> bool``

        Args:
            v: ``[int]``.
            timeout: seconds to wait for the answer (default: the bridge client's).

        Returns:
            ``bool``.

        Raises:
            ArgumentError: an argument does not match the contract (nothing is sent).
            ProviderRejection: the provider refused the call.
            ResultDecodeError: the result does not match the contract.
            MethodNotFound: this bridge does not expose the method.
        """
        result = await _BINDING.call(self._bridge, self._module, "fireIntListEvent", (v,), timeout)
        return _typing.cast("bool", result)

    async def fire_uint_list_event(self, v: _abc.Sequence[int], *, timeout: float | None = None) -> bool:
        """Call ``test_fullapi_cpp.fireUintListEvent``.

        LIDL: ``method fireUintListEvent(v: [uint]) -> bool``

        Args:
            v: ``[uint]``.
            timeout: seconds to wait for the answer (default: the bridge client's).

        Returns:
            ``bool``.

        Raises:
            ArgumentError: an argument does not match the contract (nothing is sent).
            ProviderRejection: the provider refused the call.
            ResultDecodeError: the result does not match the contract.
            MethodNotFound: this bridge does not expose the method.
        """
        result = await _BINDING.call(self._bridge, self._module, "fireUintListEvent", (v,), timeout)
        return _typing.cast("bool", result)

    async def fire_double_list_event(self, v: _abc.Sequence[float], *, timeout: float | None = None) -> bool:
        """Call ``test_fullapi_cpp.fireDoubleListEvent``.

        LIDL: ``method fireDoubleListEvent(v: [float64]) -> bool``

        Args:
            v: ``[float64]``.
            timeout: seconds to wait for the answer (default: the bridge client's).

        Returns:
            ``bool``.

        Raises:
            ArgumentError: an argument does not match the contract (nothing is sent).
            ProviderRejection: the provider refused the call.
            ResultDecodeError: the result does not match the contract.
            MethodNotFound: this bridge does not expose the method.
        """
        result = await _BINDING.call(self._bridge, self._module, "fireDoubleListEvent", (v,), timeout)
        return _typing.cast("bool", result)

    async def fire_bool_list_event(self, v: _abc.Sequence[bool], *, timeout: float | None = None) -> bool:
        """Call ``test_fullapi_cpp.fireBoolListEvent``.

        LIDL: ``method fireBoolListEvent(v: [bool]) -> bool``

        Args:
            v: ``[bool]``.
            timeout: seconds to wait for the answer (default: the bridge client's).

        Returns:
            ``bool``.

        Raises:
            ArgumentError: an argument does not match the contract (nothing is sent).
            ProviderRejection: the provider refused the call.
            ResultDecodeError: the result does not match the contract.
            MethodNotFound: this bridge does not expose the method.
        """
        result = await _BINDING.call(self._bridge, self._module, "fireBoolListEvent", (v,), timeout)
        return _typing.cast("bool", result)

    async def fire_list_event(self, v: _abc.Sequence[_typing.Any], *, timeout: float | None = None) -> bool:
        """Call ``test_fullapi_cpp.fireListEvent``.

        LIDL: ``method fireListEvent(v: [any]) -> bool``

        Args:
            v: ``[any]``.
            timeout: seconds to wait for the answer (default: the bridge client's).

        Returns:
            ``bool``.

        Raises:
            ArgumentError: an argument does not match the contract (nothing is sent).
            ProviderRejection: the provider refused the call.
            ResultDecodeError: the result does not match the contract.
            MethodNotFound: this bridge does not expose the method.
        """
        result = await _BINDING.call(self._bridge, self._module, "fireListEvent", (v,), timeout)
        return _typing.cast("bool", result)

    async def fire_map_event(
        self,
        v: _abc.Mapping[str, _typing.Any],
        *,
        timeout: float | None = None,
    ) -> bool:
        """Call ``test_fullapi_cpp.fireMapEvent``.

        LIDL: ``method fireMapEvent(v: {tstr: any}) -> bool``

        Args:
            v: ``{tstr: any}``.
            timeout: seconds to wait for the answer (default: the bridge client's).

        Returns:
            ``bool``.

        Raises:
            ArgumentError: an argument does not match the contract (nothing is sent).
            ProviderRejection: the provider refused the call.
            ResultDecodeError: the result does not match the contract.
            MethodNotFound: this bridge does not expose the method.
        """
        result = await _BINDING.call(self._bridge, self._module, "fireMapEvent", (v,), timeout)
        return _typing.cast("bool", result)

    async def fire_triple_event(self, i: int, s: str, b: bytes, *, timeout: float | None = None) -> bool:
        """Call ``test_fullapi_cpp.fireTripleEvent``.

        LIDL: ``method fireTripleEvent(i: int, s: tstr, b: bstr) -> bool``

        Args:
            i: ``int``.
            s: ``tstr``.
            b: ``bstr``.
            timeout: seconds to wait for the answer (default: the bridge client's).

        Returns:
            ``bool``.

        Raises:
            ArgumentError: an argument does not match the contract (nothing is sent).
            ProviderRejection: the provider refused the call.
            ResultDecodeError: the result does not match the contract.
            MethodNotFound: this bridge does not expose the method.
        """
        result = await _BINDING.call(self._bridge, self._module, "fireTripleEvent", (i, s, b), timeout)
        return _typing.cast("bool", result)

    async def name(self, *, timeout: float | None = None) -> str:
        """The module's name, as declared in its metadata.

        LIDL: ``method name() -> tstr`` (derived built-in)

        Args:
            timeout: seconds to wait for the answer (default: the bridge client's).

        Returns:
            ``tstr``.

        Raises:
            ArgumentError: an argument does not match the contract (nothing is sent).
            ProviderRejection: the provider refused the call.
            ResultDecodeError: the result does not match the contract.
            MethodNotFound: this bridge does not expose the method.
        """
        result = await _BINDING.call(self._bridge, self._module, "name", (), timeout)
        return _typing.cast("str", result)

    async def version(self, *, timeout: float | None = None) -> str:
        """The module's version, as declared in its metadata.

        LIDL: ``method version() -> tstr`` (derived built-in)

        Args:
            timeout: seconds to wait for the answer (default: the bridge client's).

        Returns:
            ``tstr``.

        Raises:
            ArgumentError: an argument does not match the contract (nothing is sent).
            ProviderRejection: the provider refused the call.
            ResultDecodeError: the result does not match the contract.
            MethodNotFound: this bridge does not expose the method.
        """
        result = await _BINDING.call(self._bridge, self._module, "version", (), timeout)
        return _typing.cast("str", result)

    async def lidl(self, *, timeout: float | None = None) -> str:
        """The module's canonical LIDL interface document.

        LIDL: ``method lidl() -> tstr`` (derived built-in)

        Args:
            timeout: seconds to wait for the answer (default: the bridge client's).

        Returns:
            ``tstr``.

        Raises:
            ArgumentError: an argument does not match the contract (nothing is sent).
            ProviderRejection: the provider refused the call.
            ResultDecodeError: the result does not match the contract.
            MethodNotFound: this bridge does not expose the method.
        """
        result = await _BINDING.call(self._bridge, self._module, "lidl", (), timeout)
        return _typing.cast("str", result)

    def on_string_event(
        self,
        *,
        timeout: float | None = None,
        max_pending: int | None = None,
    ) -> _t.TypedSubscribeRequest[StringEventEvent]:
        """Subscribe to ``stringEvent``: ``await`` it, or use ``async with``.

        Items are :class:`StringEventEvent`; one that does not match the contract raises
        :class:`logos_bridge.EventDecodeError` (``results()`` yields it instead).
        """
        return _BINDING.subscribe(self._bridge, self._module, ("stringEvent",), timeout, max_pending)

    def decode_string_event(self, event: _Event) -> StringEventEvent:
        """Decode a raw ``stringEvent`` event (``EventDecodeError`` if it does not match)."""
        decoded = _BINDING.decode_event("stringEvent", event)
        return _typing.cast("StringEventEvent", decoded)

    def on_bytes_event(
        self,
        *,
        timeout: float | None = None,
        max_pending: int | None = None,
    ) -> _t.TypedSubscribeRequest[BytesEventEvent]:
        """Subscribe to ``bytesEvent``: ``await`` it, or use ``async with``.

        Items are :class:`BytesEventEvent`; one that does not match the contract raises
        :class:`logos_bridge.EventDecodeError` (``results()`` yields it instead).
        """
        return _BINDING.subscribe(self._bridge, self._module, ("bytesEvent",), timeout, max_pending)

    def decode_bytes_event(self, event: _Event) -> BytesEventEvent:
        """Decode a raw ``bytesEvent`` event (``EventDecodeError`` if it does not match)."""
        decoded = _BINDING.decode_event("bytesEvent", event)
        return _typing.cast("BytesEventEvent", decoded)

    def on_int_event(
        self,
        *,
        timeout: float | None = None,
        max_pending: int | None = None,
    ) -> _t.TypedSubscribeRequest[IntEventEvent]:
        """Subscribe to ``intEvent``: ``await`` it, or use ``async with``.

        Items are :class:`IntEventEvent`; one that does not match the contract raises
        :class:`logos_bridge.EventDecodeError` (``results()`` yields it instead).
        """
        return _BINDING.subscribe(self._bridge, self._module, ("intEvent",), timeout, max_pending)

    def decode_int_event(self, event: _Event) -> IntEventEvent:
        """Decode a raw ``intEvent`` event (``EventDecodeError`` if it does not match)."""
        decoded = _BINDING.decode_event("intEvent", event)
        return _typing.cast("IntEventEvent", decoded)

    def on_uint_event(
        self,
        *,
        timeout: float | None = None,
        max_pending: int | None = None,
    ) -> _t.TypedSubscribeRequest[UintEventEvent]:
        """Subscribe to ``uintEvent``: ``await`` it, or use ``async with``.

        Items are :class:`UintEventEvent`; one that does not match the contract raises
        :class:`logos_bridge.EventDecodeError` (``results()`` yields it instead).
        """
        return _BINDING.subscribe(self._bridge, self._module, ("uintEvent",), timeout, max_pending)

    def decode_uint_event(self, event: _Event) -> UintEventEvent:
        """Decode a raw ``uintEvent`` event (``EventDecodeError`` if it does not match)."""
        decoded = _BINDING.decode_event("uintEvent", event)
        return _typing.cast("UintEventEvent", decoded)

    def on_double_event(
        self,
        *,
        timeout: float | None = None,
        max_pending: int | None = None,
    ) -> _t.TypedSubscribeRequest[DoubleEventEvent]:
        """Subscribe to ``doubleEvent``: ``await`` it, or use ``async with``.

        Items are :class:`DoubleEventEvent`; one that does not match the contract raises
        :class:`logos_bridge.EventDecodeError` (``results()`` yields it instead).
        """
        return _BINDING.subscribe(self._bridge, self._module, ("doubleEvent",), timeout, max_pending)

    def decode_double_event(self, event: _Event) -> DoubleEventEvent:
        """Decode a raw ``doubleEvent`` event (``EventDecodeError`` if it does not match)."""
        decoded = _BINDING.decode_event("doubleEvent", event)
        return _typing.cast("DoubleEventEvent", decoded)

    def on_bool_event(
        self,
        *,
        timeout: float | None = None,
        max_pending: int | None = None,
    ) -> _t.TypedSubscribeRequest[BoolEventEvent]:
        """Subscribe to ``boolEvent``: ``await`` it, or use ``async with``.

        Items are :class:`BoolEventEvent`; one that does not match the contract raises
        :class:`logos_bridge.EventDecodeError` (``results()`` yields it instead).
        """
        return _BINDING.subscribe(self._bridge, self._module, ("boolEvent",), timeout, max_pending)

    def decode_bool_event(self, event: _Event) -> BoolEventEvent:
        """Decode a raw ``boolEvent`` event (``EventDecodeError`` if it does not match)."""
        decoded = _BINDING.decode_event("boolEvent", event)
        return _typing.cast("BoolEventEvent", decoded)

    def on_any_event(
        self,
        *,
        timeout: float | None = None,
        max_pending: int | None = None,
    ) -> _t.TypedSubscribeRequest[AnyEventEvent]:
        """Subscribe to ``anyEvent``: ``await`` it, or use ``async with``.

        Items are :class:`AnyEventEvent`; one that does not match the contract raises
        :class:`logos_bridge.EventDecodeError` (``results()`` yields it instead).
        """
        return _BINDING.subscribe(self._bridge, self._module, ("anyEvent",), timeout, max_pending)

    def decode_any_event(self, event: _Event) -> AnyEventEvent:
        """Decode a raw ``anyEvent`` event (``EventDecodeError`` if it does not match)."""
        decoded = _BINDING.decode_event("anyEvent", event)
        return _typing.cast("AnyEventEvent", decoded)

    def on_string_list_event(
        self,
        *,
        timeout: float | None = None,
        max_pending: int | None = None,
    ) -> _t.TypedSubscribeRequest[StringListEventEvent]:
        """Subscribe to ``stringListEvent``: ``await`` it, or use ``async with``.

        Items are :class:`StringListEventEvent`; one that does not match the contract raises
        :class:`logos_bridge.EventDecodeError` (``results()`` yields it instead).
        """
        return _BINDING.subscribe(self._bridge, self._module, ("stringListEvent",), timeout, max_pending)

    def decode_string_list_event(self, event: _Event) -> StringListEventEvent:
        """Decode a raw ``stringListEvent`` event (``EventDecodeError`` if it does not match)."""
        decoded = _BINDING.decode_event("stringListEvent", event)
        return _typing.cast("StringListEventEvent", decoded)

    def on_int_list_event(
        self,
        *,
        timeout: float | None = None,
        max_pending: int | None = None,
    ) -> _t.TypedSubscribeRequest[IntListEventEvent]:
        """Subscribe to ``intListEvent``: ``await`` it, or use ``async with``.

        Items are :class:`IntListEventEvent`; one that does not match the contract raises
        :class:`logos_bridge.EventDecodeError` (``results()`` yields it instead).
        """
        return _BINDING.subscribe(self._bridge, self._module, ("intListEvent",), timeout, max_pending)

    def decode_int_list_event(self, event: _Event) -> IntListEventEvent:
        """Decode a raw ``intListEvent`` event (``EventDecodeError`` if it does not match)."""
        decoded = _BINDING.decode_event("intListEvent", event)
        return _typing.cast("IntListEventEvent", decoded)

    def on_uint_list_event(
        self,
        *,
        timeout: float | None = None,
        max_pending: int | None = None,
    ) -> _t.TypedSubscribeRequest[UintListEventEvent]:
        """Subscribe to ``uintListEvent``: ``await`` it, or use ``async with``.

        Items are :class:`UintListEventEvent`; one that does not match the contract raises
        :class:`logos_bridge.EventDecodeError` (``results()`` yields it instead).
        """
        return _BINDING.subscribe(self._bridge, self._module, ("uintListEvent",), timeout, max_pending)

    def decode_uint_list_event(self, event: _Event) -> UintListEventEvent:
        """Decode a raw ``uintListEvent`` event (``EventDecodeError`` if it does not match)."""
        decoded = _BINDING.decode_event("uintListEvent", event)
        return _typing.cast("UintListEventEvent", decoded)

    def on_double_list_event(
        self,
        *,
        timeout: float | None = None,
        max_pending: int | None = None,
    ) -> _t.TypedSubscribeRequest[DoubleListEventEvent]:
        """Subscribe to ``doubleListEvent``: ``await`` it, or use ``async with``.

        Items are :class:`DoubleListEventEvent`; one that does not match the contract raises
        :class:`logos_bridge.EventDecodeError` (``results()`` yields it instead).
        """
        return _BINDING.subscribe(self._bridge, self._module, ("doubleListEvent",), timeout, max_pending)

    def decode_double_list_event(self, event: _Event) -> DoubleListEventEvent:
        """Decode a raw ``doubleListEvent`` event (``EventDecodeError`` if it does not match)."""
        decoded = _BINDING.decode_event("doubleListEvent", event)
        return _typing.cast("DoubleListEventEvent", decoded)

    def on_bool_list_event(
        self,
        *,
        timeout: float | None = None,
        max_pending: int | None = None,
    ) -> _t.TypedSubscribeRequest[BoolListEventEvent]:
        """Subscribe to ``boolListEvent``: ``await`` it, or use ``async with``.

        Items are :class:`BoolListEventEvent`; one that does not match the contract raises
        :class:`logos_bridge.EventDecodeError` (``results()`` yields it instead).
        """
        return _BINDING.subscribe(self._bridge, self._module, ("boolListEvent",), timeout, max_pending)

    def decode_bool_list_event(self, event: _Event) -> BoolListEventEvent:
        """Decode a raw ``boolListEvent`` event (``EventDecodeError`` if it does not match)."""
        decoded = _BINDING.decode_event("boolListEvent", event)
        return _typing.cast("BoolListEventEvent", decoded)

    def on_list_event(
        self,
        *,
        timeout: float | None = None,
        max_pending: int | None = None,
    ) -> _t.TypedSubscribeRequest[ListEventEvent]:
        """Subscribe to ``listEvent``: ``await`` it, or use ``async with``.

        Items are :class:`ListEventEvent`; one that does not match the contract raises
        :class:`logos_bridge.EventDecodeError` (``results()`` yields it instead).
        """
        return _BINDING.subscribe(self._bridge, self._module, ("listEvent",), timeout, max_pending)

    def decode_list_event(self, event: _Event) -> ListEventEvent:
        """Decode a raw ``listEvent`` event (``EventDecodeError`` if it does not match)."""
        decoded = _BINDING.decode_event("listEvent", event)
        return _typing.cast("ListEventEvent", decoded)

    def on_map_event(
        self,
        *,
        timeout: float | None = None,
        max_pending: int | None = None,
    ) -> _t.TypedSubscribeRequest[MapEventEvent]:
        """Subscribe to ``mapEvent``: ``await`` it, or use ``async with``.

        Items are :class:`MapEventEvent`; one that does not match the contract raises
        :class:`logos_bridge.EventDecodeError` (``results()`` yields it instead).
        """
        return _BINDING.subscribe(self._bridge, self._module, ("mapEvent",), timeout, max_pending)

    def decode_map_event(self, event: _Event) -> MapEventEvent:
        """Decode a raw ``mapEvent`` event (``EventDecodeError`` if it does not match)."""
        decoded = _BINDING.decode_event("mapEvent", event)
        return _typing.cast("MapEventEvent", decoded)

    def on_triple_event(
        self,
        *,
        timeout: float | None = None,
        max_pending: int | None = None,
    ) -> _t.TypedSubscribeRequest[TripleEventEvent]:
        """Subscribe to ``tripleEvent``: ``await`` it, or use ``async with``.

        Items are :class:`TripleEventEvent`; one that does not match the contract raises
        :class:`logos_bridge.EventDecodeError` (``results()`` yields it instead).
        """
        return _BINDING.subscribe(self._bridge, self._module, ("tripleEvent",), timeout, max_pending)

    def decode_triple_event(self, event: _Event) -> TripleEventEvent:
        """Decode a raw ``tripleEvent`` event (``EventDecodeError`` if it does not match)."""
        decoded = _BINDING.decode_event("tripleEvent", event)
        return _typing.cast("TripleEventEvent", decoded)

    def events(
        self,
        *names: TestFullapiCppEventName,
        timeout: float | None = None,
        max_pending: int | None = None,
    ) -> _t.TypedSubscribeRequest[TestFullapiCppEvent]:
        """One ordered stream of the named events (every event when none are named)."""
        return _BINDING.subscribe(self._bridge, self._module, names, timeout, max_pending)

    async def check_compat(
        self,
        *,
        allow_untyped: bool = False,
        discovery_wait: float | None = 10.0,
    ) -> _CompatReport:
        """Compare the served contract with this client's (exact, shape, structural, or names).

        Waits out ``pending``; raises :class:`logos_bridge.IncompatibleModule` (or
        :class:`logos_bridge.UntypedModule` without ``allow_untyped``) when no level applies.
        Use ``report.require(methods=..., events=...)`` for the members you need.
        """
        return await _BINDING.check_compat(
            self._bridge, self._module, allow_untyped=allow_untyped, discovery_wait=discovery_wait
        )


class TestFullapiCppClient:
    """The blocking twin of :class:`AsyncTestFullapiCppClient`, over a
    :class:`logos_bridge.BridgeClient`.
    """

    def __init__(self, bridge: _BridgeClient, module: str = MODULE_NAME) -> None:
        self._bridge = bridge
        self._portal = bridge.portal
        self._aio = AsyncTestFullapiCppClient(bridge.aio, module)

    def __repr__(self) -> str:
        return f"<TestFullapiCppClient {self._aio.module} on {self._bridge.url}>"

    @property
    def aio(self) -> AsyncTestFullapiCppClient:
        return self._aio

    @property
    def bridge(self) -> _BridgeClient:
        return self._bridge

    @property
    def module(self) -> str:
        return self._aio.module

    @property
    def portal(self) -> _BlockingPortal:
        return self._portal

    def who_am_i(self, *, timeout: float | None = None) -> str:
        """Call ``test_fullapi_cpp.whoAmI``.

        LIDL: ``method whoAmI() -> tstr``

        Args:
            timeout: seconds to wait for the answer (default: the bridge client's).

        Returns:
            ``tstr``.

        Raises:
            ArgumentError: an argument does not match the contract (nothing is sent).
            ProviderRejection: the provider refused the call.
            ResultDecodeError: the result does not match the contract.
            MethodNotFound: this bridge does not expose the method.
        """
        return self._portal.call(self._aio.who_am_i, timeout=timeout)

    def echo_string(self, v: str, *, timeout: float | None = None) -> str:
        """Call ``test_fullapi_cpp.echoString``.

        LIDL: ``method echoString(v: tstr) -> tstr``

        Args:
            v: ``tstr``.
            timeout: seconds to wait for the answer (default: the bridge client's).

        Returns:
            ``tstr``.

        Raises:
            ArgumentError: an argument does not match the contract (nothing is sent).
            ProviderRejection: the provider refused the call.
            ResultDecodeError: the result does not match the contract.
            MethodNotFound: this bridge does not expose the method.
        """
        return self._portal.call(self._aio.echo_string, v, timeout=timeout)

    def echo_bytes(self, v: bytes, *, timeout: float | None = None) -> bytes:
        """Call ``test_fullapi_cpp.echoBytes``.

        LIDL: ``method echoBytes(v: bstr) -> bstr``

        Args:
            v: ``bstr``.
            timeout: seconds to wait for the answer (default: the bridge client's).

        Returns:
            ``bstr``.

        Raises:
            ArgumentError: an argument does not match the contract (nothing is sent).
            ProviderRejection: the provider refused the call.
            ResultDecodeError: the result does not match the contract.
            MethodNotFound: this bridge does not expose the method.
        """
        return self._portal.call(self._aio.echo_bytes, v, timeout=timeout)

    def echo_int(self, v: int, *, timeout: float | None = None) -> int:
        """Call ``test_fullapi_cpp.echoInt``.

        LIDL: ``method echoInt(v: int) -> int``

        Args:
            v: ``int``.
            timeout: seconds to wait for the answer (default: the bridge client's).

        Returns:
            ``int``.

        Raises:
            ArgumentError: an argument does not match the contract (nothing is sent).
            ProviderRejection: the provider refused the call.
            ResultDecodeError: the result does not match the contract.
            MethodNotFound: this bridge does not expose the method.
        """
        return self._portal.call(self._aio.echo_int, v, timeout=timeout)

    def echo_uint(self, v: int, *, timeout: float | None = None) -> int:
        """Call ``test_fullapi_cpp.echoUint``.

        LIDL: ``method echoUint(v: uint) -> uint``

        Args:
            v: ``uint``.
            timeout: seconds to wait for the answer (default: the bridge client's).

        Returns:
            ``uint``.

        Raises:
            ArgumentError: an argument does not match the contract (nothing is sent).
            ProviderRejection: the provider refused the call.
            ResultDecodeError: the result does not match the contract.
            MethodNotFound: this bridge does not expose the method.
        """
        return self._portal.call(self._aio.echo_uint, v, timeout=timeout)

    def echo_double(self, v: float, *, timeout: float | None = None) -> float:
        """Call ``test_fullapi_cpp.echoDouble``.

        LIDL: ``method echoDouble(v: float64) -> float64``

        Args:
            v: ``float64``.
            timeout: seconds to wait for the answer (default: the bridge client's).

        Returns:
            ``float64``.

        Raises:
            ArgumentError: an argument does not match the contract (nothing is sent).
            ProviderRejection: the provider refused the call.
            ResultDecodeError: the result does not match the contract.
            MethodNotFound: this bridge does not expose the method.
        """
        return self._portal.call(self._aio.echo_double, v, timeout=timeout)

    def echo_bool(self, v: bool, *, timeout: float | None = None) -> bool:
        """Call ``test_fullapi_cpp.echoBool``.

        LIDL: ``method echoBool(v: bool) -> bool``

        Args:
            v: ``bool``.
            timeout: seconds to wait for the answer (default: the bridge client's).

        Returns:
            ``bool``.

        Raises:
            ArgumentError: an argument does not match the contract (nothing is sent).
            ProviderRejection: the provider refused the call.
            ResultDecodeError: the result does not match the contract.
            MethodNotFound: this bridge does not expose the method.
        """
        return self._portal.call(self._aio.echo_bool, v, timeout=timeout)

    def echo_any(self, v: _typing.Any, *, timeout: float | None = None) -> _typing.Any:
        """Call ``test_fullapi_cpp.echoAny``.

        LIDL: ``method echoAny(v: any) -> any``

        Args:
            v: ``any``.
            timeout: seconds to wait for the answer (default: the bridge client's).

        Returns:
            ``any``.

        Raises:
            ArgumentError: an argument does not match the contract (nothing is sent).
            ProviderRejection: the provider refused the call.
                This return type can hold a value shaped like a refusal; such a value is
                reported as a rejection too.
            ResultDecodeError: the result does not match the contract.
            MethodNotFound: this bridge does not expose the method.
        """
        return self._portal.call(self._aio.echo_any, v, timeout=timeout)

    def echo_string_list(self, v: _abc.Sequence[str], *, timeout: float | None = None) -> list[str]:
        """Call ``test_fullapi_cpp.echoStringList``.

        LIDL: ``method echoStringList(v: [tstr]) -> [tstr]``

        Args:
            v: ``[tstr]``.
            timeout: seconds to wait for the answer (default: the bridge client's).

        Returns:
            ``[tstr]``.

        Raises:
            ArgumentError: an argument does not match the contract (nothing is sent).
            ProviderRejection: the provider refused the call.
            ResultDecodeError: the result does not match the contract.
            MethodNotFound: this bridge does not expose the method.
        """
        return self._portal.call(self._aio.echo_string_list, v, timeout=timeout)

    def echo_int_list(self, v: _abc.Sequence[int], *, timeout: float | None = None) -> list[int]:
        """Call ``test_fullapi_cpp.echoIntList``.

        LIDL: ``method echoIntList(v: [int]) -> [int]``

        Args:
            v: ``[int]``.
            timeout: seconds to wait for the answer (default: the bridge client's).

        Returns:
            ``[int]``.

        Raises:
            ArgumentError: an argument does not match the contract (nothing is sent).
            ProviderRejection: the provider refused the call.
            ResultDecodeError: the result does not match the contract.
            MethodNotFound: this bridge does not expose the method.
        """
        return self._portal.call(self._aio.echo_int_list, v, timeout=timeout)

    def echo_uint_list(self, v: _abc.Sequence[int], *, timeout: float | None = None) -> list[int]:
        """Call ``test_fullapi_cpp.echoUintList``.

        LIDL: ``method echoUintList(v: [uint]) -> [uint]``

        Args:
            v: ``[uint]``.
            timeout: seconds to wait for the answer (default: the bridge client's).

        Returns:
            ``[uint]``.

        Raises:
            ArgumentError: an argument does not match the contract (nothing is sent).
            ProviderRejection: the provider refused the call.
            ResultDecodeError: the result does not match the contract.
            MethodNotFound: this bridge does not expose the method.
        """
        return self._portal.call(self._aio.echo_uint_list, v, timeout=timeout)

    def echo_double_list(self, v: _abc.Sequence[float], *, timeout: float | None = None) -> list[float]:
        """Call ``test_fullapi_cpp.echoDoubleList``.

        LIDL: ``method echoDoubleList(v: [float64]) -> [float64]``

        Args:
            v: ``[float64]``.
            timeout: seconds to wait for the answer (default: the bridge client's).

        Returns:
            ``[float64]``.

        Raises:
            ArgumentError: an argument does not match the contract (nothing is sent).
            ProviderRejection: the provider refused the call.
            ResultDecodeError: the result does not match the contract.
            MethodNotFound: this bridge does not expose the method.
        """
        return self._portal.call(self._aio.echo_double_list, v, timeout=timeout)

    def echo_bool_list(self, v: _abc.Sequence[bool], *, timeout: float | None = None) -> list[bool]:
        """Call ``test_fullapi_cpp.echoBoolList``.

        LIDL: ``method echoBoolList(v: [bool]) -> [bool]``

        Args:
            v: ``[bool]``.
            timeout: seconds to wait for the answer (default: the bridge client's).

        Returns:
            ``[bool]``.

        Raises:
            ArgumentError: an argument does not match the contract (nothing is sent).
            ProviderRejection: the provider refused the call.
            ResultDecodeError: the result does not match the contract.
            MethodNotFound: this bridge does not expose the method.
        """
        return self._portal.call(self._aio.echo_bool_list, v, timeout=timeout)

    def echo_list(self, v: _abc.Sequence[_typing.Any], *, timeout: float | None = None) -> list[_typing.Any]:
        """Call ``test_fullapi_cpp.echoList``.

        LIDL: ``method echoList(v: [any]) -> [any]``

        Args:
            v: ``[any]``.
            timeout: seconds to wait for the answer (default: the bridge client's).

        Returns:
            ``[any]``.

        Raises:
            ArgumentError: an argument does not match the contract (nothing is sent).
            ProviderRejection: the provider refused the call.
            ResultDecodeError: the result does not match the contract.
            MethodNotFound: this bridge does not expose the method.
        """
        return self._portal.call(self._aio.echo_list, v, timeout=timeout)

    def echo_map(
        self,
        v: _abc.Mapping[str, _typing.Any],
        *,
        timeout: float | None = None,
    ) -> dict[str, _typing.Any]:
        """Call ``test_fullapi_cpp.echoMap``.

        LIDL: ``method echoMap(v: {tstr: any}) -> {tstr: any}``

        Args:
            v: ``{tstr: any}``.
            timeout: seconds to wait for the answer (default: the bridge client's).

        Returns:
            ``{tstr: any}``.

        Raises:
            ArgumentError: an argument does not match the contract (nothing is sent).
            ProviderRejection: the provider refused the call.
                This return type can hold a value shaped like a refusal; such a value is
                reported as a rejection too.
            ResultDecodeError: the result does not match the contract.
            MethodNotFound: this bridge does not expose the method.
        """
        return self._portal.call(self._aio.echo_map, v, timeout=timeout)

    def echo_triple(self, i: int, s: str, b: bytes, *, timeout: float | None = None) -> str:
        """Call ``test_fullapi_cpp.echoTriple``.

        LIDL: ``method echoTriple(i: int, s: tstr, b: bstr) -> tstr``

        Args:
            i: ``int``.
            s: ``tstr``.
            b: ``bstr``.
            timeout: seconds to wait for the answer (default: the bridge client's).

        Returns:
            ``tstr``.

        Raises:
            ArgumentError: an argument does not match the contract (nothing is sent).
            ProviderRejection: the provider refused the call.
            ResultDecodeError: the result does not match the contract.
            MethodNotFound: this bridge does not expose the method.
        """
        return self._portal.call(self._aio.echo_triple, i, s, b, timeout=timeout)

    def do_void(self, *, timeout: float | None = None) -> None:
        """Call ``test_fullapi_cpp.doVoid``.

        LIDL: ``method doVoid()``

        Args:
            timeout: seconds to wait for the answer (default: the bridge client's).

        Returns:
            Nothing: the method has no return value (the provider answers ``true``).

        Raises:
            ArgumentError: an argument does not match the contract (nothing is sent).
            ProviderRejection: the provider refused the call.
            ResultDecodeError: the result does not match the contract.
            MethodNotFound: this bridge does not expose the method.
        """
        self._portal.call(self._aio.do_void, timeout=timeout)

    def make_result(self, ok: bool, *, timeout: float | None = None) -> _t.LogosResult[_typing.Any]:
        """Call ``test_fullapi_cpp.makeResult``.

        LIDL: ``method makeResult(ok: bool) -> result``

        Args:
            ok: ``bool``.
            timeout: seconds to wait for the answer (default: the bridge client's).

        Returns:
            The ``result``. ``success=False`` is an answer, not an exception;
            :meth:`LogosResult.unwrap` turns it into one.

        Raises:
            ArgumentError: an argument does not match the contract (nothing is sent).
            ProviderRejection: the provider refused the call.
            ResultDecodeError: the result does not match the contract.
            MethodNotFound: this bridge does not expose the method.
        """
        return self._portal.call(self._aio.make_result, ok, timeout=timeout)

    def fire_string_event(self, v: str, *, timeout: float | None = None) -> bool:
        """Call ``test_fullapi_cpp.fireStringEvent``.

        LIDL: ``method fireStringEvent(v: tstr) -> bool``

        Args:
            v: ``tstr``.
            timeout: seconds to wait for the answer (default: the bridge client's).

        Returns:
            ``bool``.

        Raises:
            ArgumentError: an argument does not match the contract (nothing is sent).
            ProviderRejection: the provider refused the call.
            ResultDecodeError: the result does not match the contract.
            MethodNotFound: this bridge does not expose the method.
        """
        return self._portal.call(self._aio.fire_string_event, v, timeout=timeout)

    def fire_bytes_event(self, v: bytes, *, timeout: float | None = None) -> bool:
        """Call ``test_fullapi_cpp.fireBytesEvent``.

        LIDL: ``method fireBytesEvent(v: bstr) -> bool``

        Args:
            v: ``bstr``.
            timeout: seconds to wait for the answer (default: the bridge client's).

        Returns:
            ``bool``.

        Raises:
            ArgumentError: an argument does not match the contract (nothing is sent).
            ProviderRejection: the provider refused the call.
            ResultDecodeError: the result does not match the contract.
            MethodNotFound: this bridge does not expose the method.
        """
        return self._portal.call(self._aio.fire_bytes_event, v, timeout=timeout)

    def fire_int_event(self, v: int, *, timeout: float | None = None) -> bool:
        """Call ``test_fullapi_cpp.fireIntEvent``.

        LIDL: ``method fireIntEvent(v: int) -> bool``

        Args:
            v: ``int``.
            timeout: seconds to wait for the answer (default: the bridge client's).

        Returns:
            ``bool``.

        Raises:
            ArgumentError: an argument does not match the contract (nothing is sent).
            ProviderRejection: the provider refused the call.
            ResultDecodeError: the result does not match the contract.
            MethodNotFound: this bridge does not expose the method.
        """
        return self._portal.call(self._aio.fire_int_event, v, timeout=timeout)

    def fire_uint_event(self, v: int, *, timeout: float | None = None) -> bool:
        """Call ``test_fullapi_cpp.fireUintEvent``.

        LIDL: ``method fireUintEvent(v: uint) -> bool``

        Args:
            v: ``uint``.
            timeout: seconds to wait for the answer (default: the bridge client's).

        Returns:
            ``bool``.

        Raises:
            ArgumentError: an argument does not match the contract (nothing is sent).
            ProviderRejection: the provider refused the call.
            ResultDecodeError: the result does not match the contract.
            MethodNotFound: this bridge does not expose the method.
        """
        return self._portal.call(self._aio.fire_uint_event, v, timeout=timeout)

    def fire_double_event(self, v: float, *, timeout: float | None = None) -> bool:
        """Call ``test_fullapi_cpp.fireDoubleEvent``.

        LIDL: ``method fireDoubleEvent(v: float64) -> bool``

        Args:
            v: ``float64``.
            timeout: seconds to wait for the answer (default: the bridge client's).

        Returns:
            ``bool``.

        Raises:
            ArgumentError: an argument does not match the contract (nothing is sent).
            ProviderRejection: the provider refused the call.
            ResultDecodeError: the result does not match the contract.
            MethodNotFound: this bridge does not expose the method.
        """
        return self._portal.call(self._aio.fire_double_event, v, timeout=timeout)

    def fire_bool_event(self, v: bool, *, timeout: float | None = None) -> bool:
        """Call ``test_fullapi_cpp.fireBoolEvent``.

        LIDL: ``method fireBoolEvent(v: bool) -> bool``

        Args:
            v: ``bool``.
            timeout: seconds to wait for the answer (default: the bridge client's).

        Returns:
            ``bool``.

        Raises:
            ArgumentError: an argument does not match the contract (nothing is sent).
            ProviderRejection: the provider refused the call.
            ResultDecodeError: the result does not match the contract.
            MethodNotFound: this bridge does not expose the method.
        """
        return self._portal.call(self._aio.fire_bool_event, v, timeout=timeout)

    def fire_any_event(self, v: _typing.Any, *, timeout: float | None = None) -> bool:
        """Call ``test_fullapi_cpp.fireAnyEvent``.

        LIDL: ``method fireAnyEvent(v: any) -> bool``

        Args:
            v: ``any``.
            timeout: seconds to wait for the answer (default: the bridge client's).

        Returns:
            ``bool``.

        Raises:
            ArgumentError: an argument does not match the contract (nothing is sent).
            ProviderRejection: the provider refused the call.
            ResultDecodeError: the result does not match the contract.
            MethodNotFound: this bridge does not expose the method.
        """
        return self._portal.call(self._aio.fire_any_event, v, timeout=timeout)

    def fire_string_list_event(self, v: _abc.Sequence[str], *, timeout: float | None = None) -> bool:
        """Call ``test_fullapi_cpp.fireStringListEvent``.

        LIDL: ``method fireStringListEvent(v: [tstr]) -> bool``

        Args:
            v: ``[tstr]``.
            timeout: seconds to wait for the answer (default: the bridge client's).

        Returns:
            ``bool``.

        Raises:
            ArgumentError: an argument does not match the contract (nothing is sent).
            ProviderRejection: the provider refused the call.
            ResultDecodeError: the result does not match the contract.
            MethodNotFound: this bridge does not expose the method.
        """
        return self._portal.call(self._aio.fire_string_list_event, v, timeout=timeout)

    def fire_int_list_event(self, v: _abc.Sequence[int], *, timeout: float | None = None) -> bool:
        """Call ``test_fullapi_cpp.fireIntListEvent``.

        LIDL: ``method fireIntListEvent(v: [int]) -> bool``

        Args:
            v: ``[int]``.
            timeout: seconds to wait for the answer (default: the bridge client's).

        Returns:
            ``bool``.

        Raises:
            ArgumentError: an argument does not match the contract (nothing is sent).
            ProviderRejection: the provider refused the call.
            ResultDecodeError: the result does not match the contract.
            MethodNotFound: this bridge does not expose the method.
        """
        return self._portal.call(self._aio.fire_int_list_event, v, timeout=timeout)

    def fire_uint_list_event(self, v: _abc.Sequence[int], *, timeout: float | None = None) -> bool:
        """Call ``test_fullapi_cpp.fireUintListEvent``.

        LIDL: ``method fireUintListEvent(v: [uint]) -> bool``

        Args:
            v: ``[uint]``.
            timeout: seconds to wait for the answer (default: the bridge client's).

        Returns:
            ``bool``.

        Raises:
            ArgumentError: an argument does not match the contract (nothing is sent).
            ProviderRejection: the provider refused the call.
            ResultDecodeError: the result does not match the contract.
            MethodNotFound: this bridge does not expose the method.
        """
        return self._portal.call(self._aio.fire_uint_list_event, v, timeout=timeout)

    def fire_double_list_event(self, v: _abc.Sequence[float], *, timeout: float | None = None) -> bool:
        """Call ``test_fullapi_cpp.fireDoubleListEvent``.

        LIDL: ``method fireDoubleListEvent(v: [float64]) -> bool``

        Args:
            v: ``[float64]``.
            timeout: seconds to wait for the answer (default: the bridge client's).

        Returns:
            ``bool``.

        Raises:
            ArgumentError: an argument does not match the contract (nothing is sent).
            ProviderRejection: the provider refused the call.
            ResultDecodeError: the result does not match the contract.
            MethodNotFound: this bridge does not expose the method.
        """
        return self._portal.call(self._aio.fire_double_list_event, v, timeout=timeout)

    def fire_bool_list_event(self, v: _abc.Sequence[bool], *, timeout: float | None = None) -> bool:
        """Call ``test_fullapi_cpp.fireBoolListEvent``.

        LIDL: ``method fireBoolListEvent(v: [bool]) -> bool``

        Args:
            v: ``[bool]``.
            timeout: seconds to wait for the answer (default: the bridge client's).

        Returns:
            ``bool``.

        Raises:
            ArgumentError: an argument does not match the contract (nothing is sent).
            ProviderRejection: the provider refused the call.
            ResultDecodeError: the result does not match the contract.
            MethodNotFound: this bridge does not expose the method.
        """
        return self._portal.call(self._aio.fire_bool_list_event, v, timeout=timeout)

    def fire_list_event(self, v: _abc.Sequence[_typing.Any], *, timeout: float | None = None) -> bool:
        """Call ``test_fullapi_cpp.fireListEvent``.

        LIDL: ``method fireListEvent(v: [any]) -> bool``

        Args:
            v: ``[any]``.
            timeout: seconds to wait for the answer (default: the bridge client's).

        Returns:
            ``bool``.

        Raises:
            ArgumentError: an argument does not match the contract (nothing is sent).
            ProviderRejection: the provider refused the call.
            ResultDecodeError: the result does not match the contract.
            MethodNotFound: this bridge does not expose the method.
        """
        return self._portal.call(self._aio.fire_list_event, v, timeout=timeout)

    def fire_map_event(self, v: _abc.Mapping[str, _typing.Any], *, timeout: float | None = None) -> bool:
        """Call ``test_fullapi_cpp.fireMapEvent``.

        LIDL: ``method fireMapEvent(v: {tstr: any}) -> bool``

        Args:
            v: ``{tstr: any}``.
            timeout: seconds to wait for the answer (default: the bridge client's).

        Returns:
            ``bool``.

        Raises:
            ArgumentError: an argument does not match the contract (nothing is sent).
            ProviderRejection: the provider refused the call.
            ResultDecodeError: the result does not match the contract.
            MethodNotFound: this bridge does not expose the method.
        """
        return self._portal.call(self._aio.fire_map_event, v, timeout=timeout)

    def fire_triple_event(self, i: int, s: str, b: bytes, *, timeout: float | None = None) -> bool:
        """Call ``test_fullapi_cpp.fireTripleEvent``.

        LIDL: ``method fireTripleEvent(i: int, s: tstr, b: bstr) -> bool``

        Args:
            i: ``int``.
            s: ``tstr``.
            b: ``bstr``.
            timeout: seconds to wait for the answer (default: the bridge client's).

        Returns:
            ``bool``.

        Raises:
            ArgumentError: an argument does not match the contract (nothing is sent).
            ProviderRejection: the provider refused the call.
            ResultDecodeError: the result does not match the contract.
            MethodNotFound: this bridge does not expose the method.
        """
        return self._portal.call(self._aio.fire_triple_event, i, s, b, timeout=timeout)

    def name(self, *, timeout: float | None = None) -> str:
        """The module's name, as declared in its metadata.

        LIDL: ``method name() -> tstr`` (derived built-in)

        Args:
            timeout: seconds to wait for the answer (default: the bridge client's).

        Returns:
            ``tstr``.

        Raises:
            ArgumentError: an argument does not match the contract (nothing is sent).
            ProviderRejection: the provider refused the call.
            ResultDecodeError: the result does not match the contract.
            MethodNotFound: this bridge does not expose the method.
        """
        return self._portal.call(self._aio.name, timeout=timeout)

    def version(self, *, timeout: float | None = None) -> str:
        """The module's version, as declared in its metadata.

        LIDL: ``method version() -> tstr`` (derived built-in)

        Args:
            timeout: seconds to wait for the answer (default: the bridge client's).

        Returns:
            ``tstr``.

        Raises:
            ArgumentError: an argument does not match the contract (nothing is sent).
            ProviderRejection: the provider refused the call.
            ResultDecodeError: the result does not match the contract.
            MethodNotFound: this bridge does not expose the method.
        """
        return self._portal.call(self._aio.version, timeout=timeout)

    def lidl(self, *, timeout: float | None = None) -> str:
        """The module's canonical LIDL interface document.

        LIDL: ``method lidl() -> tstr`` (derived built-in)

        Args:
            timeout: seconds to wait for the answer (default: the bridge client's).

        Returns:
            ``tstr``.

        Raises:
            ArgumentError: an argument does not match the contract (nothing is sent).
            ProviderRejection: the provider refused the call.
            ResultDecodeError: the result does not match the contract.
            MethodNotFound: this bridge does not expose the method.
        """
        return self._portal.call(self._aio.lidl, timeout=timeout)

    def on_string_event(
        self,
        *,
        timeout: float | None = None,
        max_pending: int | None = None,
    ) -> _t.BlockingTypedSubscription[StringEventEvent]:
        """Subscribe to ``stringEvent``; iterate the result, and close it (or use ``with``)."""
        request = self._aio.on_string_event(timeout=timeout, max_pending=max_pending)
        return _t.BlockingTypedSubscription.open(request, self._portal)

    def decode_string_event(self, event: _Event) -> StringEventEvent:
        """Decode a raw ``stringEvent`` event."""
        return self._aio.decode_string_event(event)

    def on_bytes_event(
        self,
        *,
        timeout: float | None = None,
        max_pending: int | None = None,
    ) -> _t.BlockingTypedSubscription[BytesEventEvent]:
        """Subscribe to ``bytesEvent``; iterate the result, and close it (or use ``with``)."""
        request = self._aio.on_bytes_event(timeout=timeout, max_pending=max_pending)
        return _t.BlockingTypedSubscription.open(request, self._portal)

    def decode_bytes_event(self, event: _Event) -> BytesEventEvent:
        """Decode a raw ``bytesEvent`` event."""
        return self._aio.decode_bytes_event(event)

    def on_int_event(
        self,
        *,
        timeout: float | None = None,
        max_pending: int | None = None,
    ) -> _t.BlockingTypedSubscription[IntEventEvent]:
        """Subscribe to ``intEvent``; iterate the result, and close it (or use ``with``)."""
        request = self._aio.on_int_event(timeout=timeout, max_pending=max_pending)
        return _t.BlockingTypedSubscription.open(request, self._portal)

    def decode_int_event(self, event: _Event) -> IntEventEvent:
        """Decode a raw ``intEvent`` event."""
        return self._aio.decode_int_event(event)

    def on_uint_event(
        self,
        *,
        timeout: float | None = None,
        max_pending: int | None = None,
    ) -> _t.BlockingTypedSubscription[UintEventEvent]:
        """Subscribe to ``uintEvent``; iterate the result, and close it (or use ``with``)."""
        request = self._aio.on_uint_event(timeout=timeout, max_pending=max_pending)
        return _t.BlockingTypedSubscription.open(request, self._portal)

    def decode_uint_event(self, event: _Event) -> UintEventEvent:
        """Decode a raw ``uintEvent`` event."""
        return self._aio.decode_uint_event(event)

    def on_double_event(
        self,
        *,
        timeout: float | None = None,
        max_pending: int | None = None,
    ) -> _t.BlockingTypedSubscription[DoubleEventEvent]:
        """Subscribe to ``doubleEvent``; iterate the result, and close it (or use ``with``)."""
        request = self._aio.on_double_event(timeout=timeout, max_pending=max_pending)
        return _t.BlockingTypedSubscription.open(request, self._portal)

    def decode_double_event(self, event: _Event) -> DoubleEventEvent:
        """Decode a raw ``doubleEvent`` event."""
        return self._aio.decode_double_event(event)

    def on_bool_event(
        self,
        *,
        timeout: float | None = None,
        max_pending: int | None = None,
    ) -> _t.BlockingTypedSubscription[BoolEventEvent]:
        """Subscribe to ``boolEvent``; iterate the result, and close it (or use ``with``)."""
        request = self._aio.on_bool_event(timeout=timeout, max_pending=max_pending)
        return _t.BlockingTypedSubscription.open(request, self._portal)

    def decode_bool_event(self, event: _Event) -> BoolEventEvent:
        """Decode a raw ``boolEvent`` event."""
        return self._aio.decode_bool_event(event)

    def on_any_event(
        self,
        *,
        timeout: float | None = None,
        max_pending: int | None = None,
    ) -> _t.BlockingTypedSubscription[AnyEventEvent]:
        """Subscribe to ``anyEvent``; iterate the result, and close it (or use ``with``)."""
        request = self._aio.on_any_event(timeout=timeout, max_pending=max_pending)
        return _t.BlockingTypedSubscription.open(request, self._portal)

    def decode_any_event(self, event: _Event) -> AnyEventEvent:
        """Decode a raw ``anyEvent`` event."""
        return self._aio.decode_any_event(event)

    def on_string_list_event(
        self,
        *,
        timeout: float | None = None,
        max_pending: int | None = None,
    ) -> _t.BlockingTypedSubscription[StringListEventEvent]:
        """Subscribe to ``stringListEvent``; iterate the result, and close it (or use ``with``)."""
        request = self._aio.on_string_list_event(timeout=timeout, max_pending=max_pending)
        return _t.BlockingTypedSubscription.open(request, self._portal)

    def decode_string_list_event(self, event: _Event) -> StringListEventEvent:
        """Decode a raw ``stringListEvent`` event."""
        return self._aio.decode_string_list_event(event)

    def on_int_list_event(
        self,
        *,
        timeout: float | None = None,
        max_pending: int | None = None,
    ) -> _t.BlockingTypedSubscription[IntListEventEvent]:
        """Subscribe to ``intListEvent``; iterate the result, and close it (or use ``with``)."""
        request = self._aio.on_int_list_event(timeout=timeout, max_pending=max_pending)
        return _t.BlockingTypedSubscription.open(request, self._portal)

    def decode_int_list_event(self, event: _Event) -> IntListEventEvent:
        """Decode a raw ``intListEvent`` event."""
        return self._aio.decode_int_list_event(event)

    def on_uint_list_event(
        self,
        *,
        timeout: float | None = None,
        max_pending: int | None = None,
    ) -> _t.BlockingTypedSubscription[UintListEventEvent]:
        """Subscribe to ``uintListEvent``; iterate the result, and close it (or use ``with``)."""
        request = self._aio.on_uint_list_event(timeout=timeout, max_pending=max_pending)
        return _t.BlockingTypedSubscription.open(request, self._portal)

    def decode_uint_list_event(self, event: _Event) -> UintListEventEvent:
        """Decode a raw ``uintListEvent`` event."""
        return self._aio.decode_uint_list_event(event)

    def on_double_list_event(
        self,
        *,
        timeout: float | None = None,
        max_pending: int | None = None,
    ) -> _t.BlockingTypedSubscription[DoubleListEventEvent]:
        """Subscribe to ``doubleListEvent``; iterate the result, and close it (or use ``with``)."""
        request = self._aio.on_double_list_event(timeout=timeout, max_pending=max_pending)
        return _t.BlockingTypedSubscription.open(request, self._portal)

    def decode_double_list_event(self, event: _Event) -> DoubleListEventEvent:
        """Decode a raw ``doubleListEvent`` event."""
        return self._aio.decode_double_list_event(event)

    def on_bool_list_event(
        self,
        *,
        timeout: float | None = None,
        max_pending: int | None = None,
    ) -> _t.BlockingTypedSubscription[BoolListEventEvent]:
        """Subscribe to ``boolListEvent``; iterate the result, and close it (or use ``with``)."""
        request = self._aio.on_bool_list_event(timeout=timeout, max_pending=max_pending)
        return _t.BlockingTypedSubscription.open(request, self._portal)

    def decode_bool_list_event(self, event: _Event) -> BoolListEventEvent:
        """Decode a raw ``boolListEvent`` event."""
        return self._aio.decode_bool_list_event(event)

    def on_list_event(
        self,
        *,
        timeout: float | None = None,
        max_pending: int | None = None,
    ) -> _t.BlockingTypedSubscription[ListEventEvent]:
        """Subscribe to ``listEvent``; iterate the result, and close it (or use ``with``)."""
        request = self._aio.on_list_event(timeout=timeout, max_pending=max_pending)
        return _t.BlockingTypedSubscription.open(request, self._portal)

    def decode_list_event(self, event: _Event) -> ListEventEvent:
        """Decode a raw ``listEvent`` event."""
        return self._aio.decode_list_event(event)

    def on_map_event(
        self,
        *,
        timeout: float | None = None,
        max_pending: int | None = None,
    ) -> _t.BlockingTypedSubscription[MapEventEvent]:
        """Subscribe to ``mapEvent``; iterate the result, and close it (or use ``with``)."""
        request = self._aio.on_map_event(timeout=timeout, max_pending=max_pending)
        return _t.BlockingTypedSubscription.open(request, self._portal)

    def decode_map_event(self, event: _Event) -> MapEventEvent:
        """Decode a raw ``mapEvent`` event."""
        return self._aio.decode_map_event(event)

    def on_triple_event(
        self,
        *,
        timeout: float | None = None,
        max_pending: int | None = None,
    ) -> _t.BlockingTypedSubscription[TripleEventEvent]:
        """Subscribe to ``tripleEvent``; iterate the result, and close it (or use ``with``)."""
        request = self._aio.on_triple_event(timeout=timeout, max_pending=max_pending)
        return _t.BlockingTypedSubscription.open(request, self._portal)

    def decode_triple_event(self, event: _Event) -> TripleEventEvent:
        """Decode a raw ``tripleEvent`` event."""
        return self._aio.decode_triple_event(event)

    def events(
        self,
        *names: TestFullapiCppEventName,
        timeout: float | None = None,
        max_pending: int | None = None,
    ) -> _t.BlockingTypedSubscription[TestFullapiCppEvent]:
        """One ordered, blocking stream of the named events (every event when none are named)."""
        request = self._aio.events(*names, timeout=timeout, max_pending=max_pending)
        return _t.BlockingTypedSubscription.open(request, self._portal)

    def check_compat(
        self,
        *,
        allow_untyped: bool = False,
        discovery_wait: float | None = 10.0,
    ) -> _CompatReport:
        """Blocking :meth:`AsyncTestFullapiCppClient.check_compat`."""
        return self._portal.call(
            self._aio.check_compat, allow_untyped=allow_untyped, discovery_wait=discovery_wait
        )
