# GENERATED by logos-bridge-codegen. Do not edit: regenerate instead.
# Contract: test_fullapi_ext_cpp 1.0.0
# INTERFACE_SHA256: 435ba4bdc7c854b718a2584e4252cbe6a25b85727286b890b6dfccb29f238e5d
# CONTRACT_SHA256: 7308b6432d35a7e367dc33219e9c059c59faac89a3aabd05b2b6984f934bd1fe
# SHAPE_SHA256: 7ef826b134ad1ef775d8b396d8ff669671fea5255383e9b0725fe6ad966ede16
# Codegen format: 1
# Regenerate: nix run .#regen-goldens
# Source: lidl tests/fixtures/lidl/test_fullapi_ext_cpp.lidl
# Generator: logos-bridge 0.1.0; reader: lidl 0.1.0 (2043d8b)
"""Typed client for the ``test_fullapi_ext_cpp`` module (LIDL contract 1.0.0).

C++ mirror of test_fullapi_ext_rust, HEADER-FIRST like test_fullapi_cpp: the contract is derived
from the impl header, records included. Keeps the two ext providers comparable cell for cell.

Clients: :class:`AsyncTestFullapiExtCppClient` (asyncio, on a connected
:class:`logos_bridge.AsyncBridgeClient`) and :class:`TestFullapiExtCppClient` (blocking, on a
:class:`logos_bridge.BridgeClient`). Every call goes through ``rpc.call``.
Run ``check_compat()`` after connecting, and again after a subscription ends
with ``provider_changed``.
"""

from __future__ import annotations

import builtins as _builtins
import dataclasses as _dataclasses
import typing as _typing
from collections import abc as _abc

from logos_bridge import typed as _t
from logos_bridge.client import AsyncBridgeClient as _AsyncBridgeClient
from logos_bridge.compat import CompatReport as _CompatReport
from logos_bridge.models import Event as _Event
from logos_bridge.portal import BlockingPortal as _BlockingPortal
from logos_bridge.sync import BridgeClient as _BridgeClient

_t.require_codegen_format(1)

MODULE_NAME: _typing.Final = "test_fullapi_ext_cpp"
INTERFACE_SHA256: _typing.Final = "435ba4bdc7c854b718a2584e4252cbe6a25b85727286b890b6dfccb29f238e5d"
CONTRACT_SHA256: _typing.Final[str | None] = (
    "7308b6432d35a7e367dc33219e9c059c59faac89a3aabd05b2b6984f934bd1fe"
)
SHAPE_SHA256: _typing.Final = "7ef826b134ad1ef775d8b396d8ff669671fea5255383e9b0725fe6ad966ede16"

# The contract's shape (see logos_bridge.lidl.Interface.shape), checked at import.
INTERFACE: _typing.Final[_abc.Mapping[str, _typing.Any]] = {
    "shape": 1,
    "module": "test_fullapi_ext_cpp",
    "records": {
        "Blob": {"id": "tstr", "n": "uint", "payload": "bstr"},
        "Wrapper": {"inner": "Blob", "tags": "[tstr]", "blobs": "[Blob]"},
        "Opt": {"required": "tstr", "maybe": "?tstr", "count": "?uint", "blob": "?bstr"},
    },
    "methods": {
        "whoAmI": {"params": [], "returns": "tstr"},
        "echoBlob": {"params": [["v", "Blob"]], "returns": "Blob"},
        "echoWrapper": {"params": [["v", "Wrapper"]], "returns": "Wrapper"},
        "echoBlobList": {"params": [["v", "[Blob]"]], "returns": "[Blob]"},
        "echoBlobMap": {"params": [["v", "{tstr:Blob}"]], "returns": "{tstr:Blob}"},
        "echoBytesList": {"params": [["v", "[bstr]"]], "returns": "[bstr]"},
        "echoBytesMap": {"params": [["v", "{tstr:bstr}"]], "returns": "{tstr:bstr}"},
        "echoIntMap": {"params": [["v", "{tstr:int}"]], "returns": "{tstr:int}"},
        "echoStringMap": {"params": [["v", "{tstr:tstr}"]], "returns": "{tstr:tstr}"},
        "echoNestedInts": {"params": [["v", "[[int]]"]], "returns": "[[int]]"},
        "echoMapOfBytesLists": {"params": [["v", "{tstr:[bstr]}"]], "returns": "{tstr:[bstr]}"},
        "echoOpt": {"params": [["v", "Opt"]], "returns": "Opt"},
        "echoOptList": {"params": [["v", "[Opt]"]], "returns": "[Opt]"},
        "echoOptional": {"params": [["v", "?tstr"]], "returns": "?tstr"},
        "fireBlobEvent": {"params": [["v", "Blob"]], "returns": "bool"},
        "name": {"params": [], "returns": "tstr"},
        "version": {"params": [], "returns": "tstr"},
        "lidl": {"params": [], "returns": "tstr"},
    },
    "events": {"blobEvent": [["v", "Blob"]]},
}


@_dataclasses.dataclass(frozen=True, slots=True, kw_only=True)
class Blob:
    """LIDL record ``Blob``.

    Attributes:
        id: ``id: tstr``
        n: ``n: uint``
        payload: ``payload: bstr``
    """

    id: str = _dataclasses.field(metadata={"lidl": "id"})
    n: int = _dataclasses.field(metadata={"lidl": "n"})
    payload: bytes = _dataclasses.field(metadata={"lidl": "payload"})


@_dataclasses.dataclass(frozen=True, slots=True, kw_only=True)
class Wrapper:
    """LIDL record ``Wrapper``.

    Attributes:
        inner: ``inner: Blob``
        tags: ``tags: [tstr]``
        blobs: ``blobs: [Blob]``
    """

    inner: Blob = _dataclasses.field(metadata={"lidl": "inner"})
    tags: list[str] = _dataclasses.field(metadata={"lidl": "tags"})
    blobs: list[Blob] = _dataclasses.field(metadata={"lidl": "blobs"})


@_dataclasses.dataclass(frozen=True, slots=True, kw_only=True)
class Opt:
    """LIDL record ``Opt``.

    Attributes:
        required: ``required: tstr``
        maybe: ``maybe: ? tstr`` (optional; omitted from the wire when ``None``)
        count: ``count: ? uint`` (optional; omitted from the wire when ``None``)
        blob: ``blob: ? bstr`` (optional; omitted from the wire when ``None``)
    """

    required: str = _dataclasses.field(metadata={"lidl": "required"})
    maybe: str | None = _dataclasses.field(default=None, metadata={"lidl": "maybe"})
    count: int | None = _dataclasses.field(default=None, metadata={"lidl": "count"})
    blob: bytes | None = _dataclasses.field(default=None, metadata={"lidl": "blob"})


@_dataclasses.dataclass(frozen=True, slots=True, kw_only=True)
class BlobEventEvent:
    """The ``blobEvent`` event.

    LIDL: ``event blobEvent(v: Blob)``

    Attributes:
        v: ``Blob``
        meta: the raw event (subscription, generation, ts, data).
    """

    v: Blob = _dataclasses.field(metadata={"lidl": "v"})
    meta: _Event


TestFullapiExtCppEvent: _typing.TypeAlias = BlobEventEvent
TestFullapiExtCppEventName: _typing.TypeAlias = _typing.Literal["blobEvent"]
EVENT_NAMES: _typing.Final[tuple[TestFullapiExtCppEventName, ...]] = ("blobEvent",)
RECORD_TYPES: _typing.Final[_abc.Mapping[str, type]] = {"Blob": Blob, "Wrapper": Wrapper, "Opt": Opt}
EVENT_TYPES: _typing.Final[_abc.Mapping[str, type]] = {"blobEvent": BlobEventEvent}

_BINDING: _typing.Final = _t.Binding(
    INTERFACE, SHAPE_SHA256, INTERFACE_SHA256, records=RECORD_TYPES, events=EVENT_TYPES
)


class AsyncTestFullapiExtCppClient:
    """``test_fullapi_ext_cpp`` over an :class:`logos_bridge.AsyncBridgeClient`.

    ``module`` is the bridge module name to call (default ``test_fullapi_ext_cpp``).
    """

    def __init__(self, bridge: _AsyncBridgeClient, module: str = MODULE_NAME) -> None:
        self._bridge = bridge
        self._module = module

    def __repr__(self) -> str:
        return f"<AsyncTestFullapiExtCppClient {self._module} on {self._bridge.url}>"

    @property
    def bridge(self) -> _AsyncBridgeClient:
        return self._bridge

    @property
    def module(self) -> str:
        return self._module

    async def who_am_i(self, *, timeout: float | None = None) -> str:
        """Call ``test_fullapi_ext_cpp.whoAmI``.

        LIDL: ``method whoAmI() -> tstr``

        Args:
            timeout: seconds to wait for the answer (default: the bridge client's).

        Returns:
            ``tstr``.

        Raises:
            ArgumentError: an argument does not match the contract (nothing is sent).
            ProviderRejection: the provider refused the call.
            ResultDecodeError: the result does not match the contract.
            MethodNotFound: this bridge does not expose the method.
        """
        result = await _BINDING.call(self._bridge, self._module, "whoAmI", (), timeout)
        return _typing.cast("str", result)

    async def echo_blob(self, v: Blob, *, timeout: float | None = None) -> Blob:
        """Call ``test_fullapi_ext_cpp.echoBlob``.

        LIDL: ``method echoBlob(v: Blob) -> Blob``

        Args:
            v: ``Blob``.
            timeout: seconds to wait for the answer (default: the bridge client's).

        Returns:
            ``Blob``.

        Raises:
            ArgumentError: an argument does not match the contract (nothing is sent).
            ProviderRejection: the provider refused the call.
            ResultDecodeError: the result does not match the contract.
            MethodNotFound: this bridge does not expose the method.
        """
        result = await _BINDING.call(self._bridge, self._module, "echoBlob", (v,), timeout)
        return _typing.cast("Blob", result)

    async def echo_wrapper(self, v: Wrapper, *, timeout: float | None = None) -> Wrapper:
        """Call ``test_fullapi_ext_cpp.echoWrapper``.

        LIDL: ``method echoWrapper(v: Wrapper) -> Wrapper``

        Args:
            v: ``Wrapper``.
            timeout: seconds to wait for the answer (default: the bridge client's).

        Returns:
            ``Wrapper``.

        Raises:
            ArgumentError: an argument does not match the contract (nothing is sent).
            ProviderRejection: the provider refused the call.
            ResultDecodeError: the result does not match the contract.
            MethodNotFound: this bridge does not expose the method.
        """
        result = await _BINDING.call(self._bridge, self._module, "echoWrapper", (v,), timeout)
        return _typing.cast("Wrapper", result)

    async def echo_blob_list(self, v: _abc.Sequence[Blob], *, timeout: float | None = None) -> list[Blob]:
        """Call ``test_fullapi_ext_cpp.echoBlobList``.

        LIDL: ``method echoBlobList(v: [Blob]) -> [Blob]``

        Args:
            v: ``[Blob]``.
            timeout: seconds to wait for the answer (default: the bridge client's).

        Returns:
            ``[Blob]``.

        Raises:
            ArgumentError: an argument does not match the contract (nothing is sent).
            ProviderRejection: the provider refused the call.
            ResultDecodeError: the result does not match the contract.
            MethodNotFound: this bridge does not expose the method.
        """
        result = await _BINDING.call(self._bridge, self._module, "echoBlobList", (v,), timeout)
        return _typing.cast("list[Blob]", result)

    async def echo_blob_map(
        self,
        v: _abc.Mapping[str, Blob],
        *,
        timeout: float | None = None,
    ) -> dict[str, Blob]:
        """Call ``test_fullapi_ext_cpp.echoBlobMap``.

        LIDL: ``method echoBlobMap(v: {tstr: Blob}) -> {tstr: Blob}``

        Args:
            v: ``{tstr: Blob}``.
            timeout: seconds to wait for the answer (default: the bridge client's).

        Returns:
            ``{tstr: Blob}``.

        Raises:
            ArgumentError: an argument does not match the contract (nothing is sent).
            ProviderRejection: the provider refused the call.
            ResultDecodeError: the result does not match the contract.
            MethodNotFound: this bridge does not expose the method.
        """
        result = await _BINDING.call(self._bridge, self._module, "echoBlobMap", (v,), timeout)
        return _typing.cast("dict[str, Blob]", result)

    async def echo_bytes_list(self, v: _abc.Sequence[bytes], *, timeout: float | None = None) -> list[bytes]:
        """Call ``test_fullapi_ext_cpp.echoBytesList``.

        LIDL: ``method echoBytesList(v: [bstr]) -> [bstr]``

        Args:
            v: ``[bstr]``.
            timeout: seconds to wait for the answer (default: the bridge client's).

        Returns:
            ``[bstr]``.

        Raises:
            ArgumentError: an argument does not match the contract (nothing is sent).
            ProviderRejection: the provider refused the call.
            ResultDecodeError: the result does not match the contract.
            MethodNotFound: this bridge does not expose the method.
        """
        result = await _BINDING.call(self._bridge, self._module, "echoBytesList", (v,), timeout)
        return _typing.cast("list[bytes]", result)

    async def echo_bytes_map(
        self,
        v: _abc.Mapping[str, bytes],
        *,
        timeout: float | None = None,
    ) -> dict[str, bytes]:
        """Call ``test_fullapi_ext_cpp.echoBytesMap``.

        LIDL: ``method echoBytesMap(v: {tstr: bstr}) -> {tstr: bstr}``

        Args:
            v: ``{tstr: bstr}``.
            timeout: seconds to wait for the answer (default: the bridge client's).

        Returns:
            ``{tstr: bstr}``.

        Raises:
            ArgumentError: an argument does not match the contract (nothing is sent).
            ProviderRejection: the provider refused the call.
            ResultDecodeError: the result does not match the contract.
            MethodNotFound: this bridge does not expose the method.
        """
        result = await _BINDING.call(self._bridge, self._module, "echoBytesMap", (v,), timeout)
        return _typing.cast("dict[str, bytes]", result)

    async def echo_int_map(
        self,
        v: _abc.Mapping[str, int],
        *,
        timeout: float | None = None,
    ) -> dict[str, int]:
        """Call ``test_fullapi_ext_cpp.echoIntMap``.

        LIDL: ``method echoIntMap(v: {tstr: int}) -> {tstr: int}``

        Args:
            v: ``{tstr: int}``.
            timeout: seconds to wait for the answer (default: the bridge client's).

        Returns:
            ``{tstr: int}``.

        Raises:
            ArgumentError: an argument does not match the contract (nothing is sent).
            ProviderRejection: the provider refused the call.
            ResultDecodeError: the result does not match the contract.
            MethodNotFound: this bridge does not expose the method.
        """
        result = await _BINDING.call(self._bridge, self._module, "echoIntMap", (v,), timeout)
        return _typing.cast("dict[str, int]", result)

    async def echo_string_map(
        self,
        v: _abc.Mapping[str, str],
        *,
        timeout: float | None = None,
    ) -> dict[str, str]:
        """Call ``test_fullapi_ext_cpp.echoStringMap``.

        LIDL: ``method echoStringMap(v: {tstr: tstr}) -> {tstr: tstr}``

        Args:
            v: ``{tstr: tstr}``.
            timeout: seconds to wait for the answer (default: the bridge client's).

        Returns:
            ``{tstr: tstr}``.

        Raises:
            ArgumentError: an argument does not match the contract (nothing is sent).
            ProviderRejection: the provider refused the call.
                This return type can hold a value shaped like a refusal; such a value is
                reported as a rejection too.
            ResultDecodeError: the result does not match the contract.
            MethodNotFound: this bridge does not expose the method.
        """
        result = await _BINDING.call(self._bridge, self._module, "echoStringMap", (v,), timeout)
        return _typing.cast("dict[str, str]", result)

    async def echo_nested_ints(
        self,
        v: _abc.Sequence[_abc.Sequence[int]],
        *,
        timeout: float | None = None,
    ) -> list[list[int]]:
        """Call ``test_fullapi_ext_cpp.echoNestedInts``.

        LIDL: ``method echoNestedInts(v: [[int]]) -> [[int]]``

        Args:
            v: ``[[int]]``.
            timeout: seconds to wait for the answer (default: the bridge client's).

        Returns:
            ``[[int]]``.

        Raises:
            ArgumentError: an argument does not match the contract (nothing is sent).
            ProviderRejection: the provider refused the call.
            ResultDecodeError: the result does not match the contract.
            MethodNotFound: this bridge does not expose the method.
        """
        result = await _BINDING.call(self._bridge, self._module, "echoNestedInts", (v,), timeout)
        return _typing.cast("list[list[int]]", result)

    async def echo_map_of_bytes_lists(
        self,
        v: _abc.Mapping[str, _abc.Sequence[bytes]],
        *,
        timeout: float | None = None,
    ) -> dict[str, list[bytes]]:
        """Call ``test_fullapi_ext_cpp.echoMapOfBytesLists``.

        LIDL: ``method echoMapOfBytesLists(v: {tstr: [bstr]}) -> {tstr: [bstr]}``

        Args:
            v: ``{tstr: [bstr]}``.
            timeout: seconds to wait for the answer (default: the bridge client's).

        Returns:
            ``{tstr: [bstr]}``.

        Raises:
            ArgumentError: an argument does not match the contract (nothing is sent).
            ProviderRejection: the provider refused the call.
            ResultDecodeError: the result does not match the contract.
            MethodNotFound: this bridge does not expose the method.
        """
        result = await _BINDING.call(self._bridge, self._module, "echoMapOfBytesLists", (v,), timeout)
        return _typing.cast("dict[str, list[bytes]]", result)

    async def echo_opt(self, v: Opt, *, timeout: float | None = None) -> Opt:
        """Call ``test_fullapi_ext_cpp.echoOpt``.

        LIDL: ``method echoOpt(v: Opt) -> Opt``

        Args:
            v: ``Opt``.
            timeout: seconds to wait for the answer (default: the bridge client's).

        Returns:
            ``Opt``.

        Raises:
            ArgumentError: an argument does not match the contract (nothing is sent).
            ProviderRejection: the provider refused the call.
            ResultDecodeError: the result does not match the contract.
            MethodNotFound: this bridge does not expose the method.
        """
        result = await _BINDING.call(self._bridge, self._module, "echoOpt", (v,), timeout)
        return _typing.cast("Opt", result)

    async def echo_opt_list(self, v: _abc.Sequence[Opt], *, timeout: float | None = None) -> list[Opt]:
        """Call ``test_fullapi_ext_cpp.echoOptList``.

        LIDL: ``method echoOptList(v: [Opt]) -> [Opt]``

        Args:
            v: ``[Opt]``.
            timeout: seconds to wait for the answer (default: the bridge client's).

        Returns:
            ``[Opt]``.

        Raises:
            ArgumentError: an argument does not match the contract (nothing is sent).
            ProviderRejection: the provider refused the call.
            ResultDecodeError: the result does not match the contract.
            MethodNotFound: this bridge does not expose the method.
        """
        result = await _BINDING.call(self._bridge, self._module, "echoOptList", (v,), timeout)
        return _typing.cast("list[Opt]", result)

    async def echo_optional(self, v: str | None = None, *, timeout: float | None = None) -> str | None:
        """Call ``test_fullapi_ext_cpp.echoOptional``.

        LIDL: ``method echoOptional(v: ? tstr) -> ? tstr``

        Args:
            v: ``? tstr`` (optional).
            timeout: seconds to wait for the answer (default: the bridge client's).

        Returns:
            ``? tstr``.

        Raises:
            ArgumentError: an argument does not match the contract (nothing is sent).
            ProviderRejection: the provider refused the call.
            ResultDecodeError: the result does not match the contract.
            MethodNotFound: this bridge does not expose the method.
        """
        result = await _BINDING.call(self._bridge, self._module, "echoOptional", (v,), timeout)
        return _typing.cast("str | None", result)

    async def fire_blob_event(self, v: Blob, *, timeout: float | None = None) -> bool:
        """Call ``test_fullapi_ext_cpp.fireBlobEvent``.

        LIDL: ``method fireBlobEvent(v: Blob) -> bool``

        Args:
            v: ``Blob``.
            timeout: seconds to wait for the answer (default: the bridge client's).

        Returns:
            ``bool``.

        Raises:
            ArgumentError: an argument does not match the contract (nothing is sent).
            ProviderRejection: the provider refused the call.
            ResultDecodeError: the result does not match the contract.
            MethodNotFound: this bridge does not expose the method.
        """
        result = await _BINDING.call(self._bridge, self._module, "fireBlobEvent", (v,), timeout)
        return _typing.cast("bool", result)

    async def name(self, *, timeout: float | None = None) -> str:
        """The module's name, as declared in its metadata.

        LIDL: ``method name() -> tstr`` (derived built-in)

        Args:
            timeout: seconds to wait for the answer (default: the bridge client's).

        Returns:
            ``tstr``.

        Raises:
            ArgumentError: an argument does not match the contract (nothing is sent).
            ProviderRejection: the provider refused the call.
            ResultDecodeError: the result does not match the contract.
            MethodNotFound: this bridge does not expose the method.
        """
        result = await _BINDING.call(self._bridge, self._module, "name", (), timeout)
        return _typing.cast("str", result)

    async def version(self, *, timeout: float | None = None) -> str:
        """The module's version, as declared in its metadata.

        LIDL: ``method version() -> tstr`` (derived built-in)

        Args:
            timeout: seconds to wait for the answer (default: the bridge client's).

        Returns:
            ``tstr``.

        Raises:
            ArgumentError: an argument does not match the contract (nothing is sent).
            ProviderRejection: the provider refused the call.
            ResultDecodeError: the result does not match the contract.
            MethodNotFound: this bridge does not expose the method.
        """
        result = await _BINDING.call(self._bridge, self._module, "version", (), timeout)
        return _typing.cast("str", result)

    async def lidl(self, *, timeout: float | None = None) -> str:
        """The module's canonical LIDL interface document.

        LIDL: ``method lidl() -> tstr`` (derived built-in)

        Args:
            timeout: seconds to wait for the answer (default: the bridge client's).

        Returns:
            ``tstr``.

        Raises:
            ArgumentError: an argument does not match the contract (nothing is sent).
            ProviderRejection: the provider refused the call.
            ResultDecodeError: the result does not match the contract.
            MethodNotFound: this bridge does not expose the method.
        """
        result = await _BINDING.call(self._bridge, self._module, "lidl", (), timeout)
        return _typing.cast("str", result)

    def on_blob_event(
        self,
        *,
        timeout: float | None = None,
        max_pending: int | None = None,
    ) -> _t.TypedSubscribeRequest[BlobEventEvent]:
        """Subscribe to ``blobEvent``: ``await`` it, or use ``async with``.

        Items are :class:`BlobEventEvent`; one that does not match the contract raises
        :class:`logos_bridge.EventDecodeError` (``results()`` yields it instead).
        """
        return _BINDING.subscribe(self._bridge, self._module, ("blobEvent",), timeout, max_pending)

    def decode_blob_event(self, event: _Event) -> BlobEventEvent:
        """Decode a raw ``blobEvent`` event (``EventDecodeError`` if it does not match)."""
        decoded = _BINDING.decode_event("blobEvent", event)
        return _typing.cast("BlobEventEvent", decoded)

    def events(
        self,
        *names: TestFullapiExtCppEventName,
        timeout: float | None = None,
        max_pending: int | None = None,
    ) -> _t.TypedSubscribeRequest[TestFullapiExtCppEvent]:
        """One ordered stream of the named events (every event when none are named)."""
        return _BINDING.subscribe(self._bridge, self._module, names, timeout, max_pending)

    async def check_compat(
        self,
        *,
        allow_untyped: bool = False,
        discovery_wait: float | None = 10.0,
    ) -> _CompatReport:
        """Compare the served contract with this client's (exact, shape, structural, or names).

        Waits out ``pending``; raises :class:`logos_bridge.IncompatibleModule` (or
        :class:`logos_bridge.UntypedModule` without ``allow_untyped``) when no level applies.
        Use ``report.require(methods=..., events=...)`` for the members you need.
        """
        return await _BINDING.check_compat(
            self._bridge, self._module, allow_untyped=allow_untyped, discovery_wait=discovery_wait
        )


class TestFullapiExtCppClient:
    """The blocking twin of :class:`AsyncTestFullapiExtCppClient`, over a
    :class:`logos_bridge.BridgeClient`.
    """

    def __init__(self, bridge: _BridgeClient, module: str = MODULE_NAME) -> None:
        self._bridge = bridge
        self._portal = bridge.portal
        self._aio = AsyncTestFullapiExtCppClient(bridge.aio, module)

    def __repr__(self) -> str:
        return f"<TestFullapiExtCppClient {self._aio.module} on {self._bridge.url}>"

    @property
    def aio(self) -> AsyncTestFullapiExtCppClient:
        return self._aio

    @property
    def bridge(self) -> _BridgeClient:
        return self._bridge

    @property
    def module(self) -> str:
        return self._aio.module

    @property
    def portal(self) -> _BlockingPortal:
        return self._portal

    def who_am_i(self, *, timeout: float | None = None) -> str:
        """Call ``test_fullapi_ext_cpp.whoAmI``.

        LIDL: ``method whoAmI() -> tstr``

        Args:
            timeout: seconds to wait for the answer (default: the bridge client's).

        Returns:
            ``tstr``.

        Raises:
            ArgumentError: an argument does not match the contract (nothing is sent).
            ProviderRejection: the provider refused the call.
            ResultDecodeError: the result does not match the contract.
            MethodNotFound: this bridge does not expose the method.
        """
        return self._portal.call(self._aio.who_am_i, timeout=timeout)

    def echo_blob(self, v: Blob, *, timeout: float | None = None) -> Blob:
        """Call ``test_fullapi_ext_cpp.echoBlob``.

        LIDL: ``method echoBlob(v: Blob) -> Blob``

        Args:
            v: ``Blob``.
            timeout: seconds to wait for the answer (default: the bridge client's).

        Returns:
            ``Blob``.

        Raises:
            ArgumentError: an argument does not match the contract (nothing is sent).
            ProviderRejection: the provider refused the call.
            ResultDecodeError: the result does not match the contract.
            MethodNotFound: this bridge does not expose the method.
        """
        return self._portal.call(self._aio.echo_blob, v, timeout=timeout)

    def echo_wrapper(self, v: Wrapper, *, timeout: float | None = None) -> Wrapper:
        """Call ``test_fullapi_ext_cpp.echoWrapper``.

        LIDL: ``method echoWrapper(v: Wrapper) -> Wrapper``

        Args:
            v: ``Wrapper``.
            timeout: seconds to wait for the answer (default: the bridge client's).

        Returns:
            ``Wrapper``.

        Raises:
            ArgumentError: an argument does not match the contract (nothing is sent).
            ProviderRejection: the provider refused the call.
            ResultDecodeError: the result does not match the contract.
            MethodNotFound: this bridge does not expose the method.
        """
        return self._portal.call(self._aio.echo_wrapper, v, timeout=timeout)

    def echo_blob_list(self, v: _abc.Sequence[Blob], *, timeout: float | None = None) -> list[Blob]:
        """Call ``test_fullapi_ext_cpp.echoBlobList``.

        LIDL: ``method echoBlobList(v: [Blob]) -> [Blob]``

        Args:
            v: ``[Blob]``.
            timeout: seconds to wait for the answer (default: the bridge client's).

        Returns:
            ``[Blob]``.

        Raises:
            ArgumentError: an argument does not match the contract (nothing is sent).
            ProviderRejection: the provider refused the call.
            ResultDecodeError: the result does not match the contract.
            MethodNotFound: this bridge does not expose the method.
        """
        return self._portal.call(self._aio.echo_blob_list, v, timeout=timeout)

    def echo_blob_map(self, v: _abc.Mapping[str, Blob], *, timeout: float | None = None) -> dict[str, Blob]:
        """Call ``test_fullapi_ext_cpp.echoBlobMap``.

        LIDL: ``method echoBlobMap(v: {tstr: Blob}) -> {tstr: Blob}``

        Args:
            v: ``{tstr: Blob}``.
            timeout: seconds to wait for the answer (default: the bridge client's).

        Returns:
            ``{tstr: Blob}``.

        Raises:
            ArgumentError: an argument does not match the contract (nothing is sent).
            ProviderRejection: the provider refused the call.
            ResultDecodeError: the result does not match the contract.
            MethodNotFound: this bridge does not expose the method.
        """
        return self._portal.call(self._aio.echo_blob_map, v, timeout=timeout)

    def echo_bytes_list(self, v: _abc.Sequence[bytes], *, timeout: float | None = None) -> list[bytes]:
        """Call ``test_fullapi_ext_cpp.echoBytesList``.

        LIDL: ``method echoBytesList(v: [bstr]) -> [bstr]``

        Args:
            v: ``[bstr]``.
            timeout: seconds to wait for the answer (default: the bridge client's).

        Returns:
            ``[bstr]``.

        Raises:
            ArgumentError: an argument does not match the contract (nothing is sent).
            ProviderRejection: the provider refused the call.
            ResultDecodeError: the result does not match the contract.
            MethodNotFound: this bridge does not expose the method.
        """
        return self._portal.call(self._aio.echo_bytes_list, v, timeout=timeout)

    def echo_bytes_map(
        self,
        v: _abc.Mapping[str, bytes],
        *,
        timeout: float | None = None,
    ) -> dict[str, bytes]:
        """Call ``test_fullapi_ext_cpp.echoBytesMap``.

        LIDL: ``method echoBytesMap(v: {tstr: bstr}) -> {tstr: bstr}``

        Args:
            v: ``{tstr: bstr}``.
            timeout: seconds to wait for the answer (default: the bridge client's).

        Returns:
            ``{tstr: bstr}``.

        Raises:
            ArgumentError: an argument does not match the contract (nothing is sent).
            ProviderRejection: the provider refused the call.
            ResultDecodeError: the result does not match the contract.
            MethodNotFound: this bridge does not expose the method.
        """
        return self._portal.call(self._aio.echo_bytes_map, v, timeout=timeout)

    def echo_int_map(self, v: _abc.Mapping[str, int], *, timeout: float | None = None) -> dict[str, int]:
        """Call ``test_fullapi_ext_cpp.echoIntMap``.

        LIDL: ``method echoIntMap(v: {tstr: int}) -> {tstr: int}``

        Args:
            v: ``{tstr: int}``.
            timeout: seconds to wait for the answer (default: the bridge client's).

        Returns:
            ``{tstr: int}``.

        Raises:
            ArgumentError: an argument does not match the contract (nothing is sent).
            ProviderRejection: the provider refused the call.
            ResultDecodeError: the result does not match the contract.
            MethodNotFound: this bridge does not expose the method.
        """
        return self._portal.call(self._aio.echo_int_map, v, timeout=timeout)

    def echo_string_map(self, v: _abc.Mapping[str, str], *, timeout: float | None = None) -> dict[str, str]:
        """Call ``test_fullapi_ext_cpp.echoStringMap``.

        LIDL: ``method echoStringMap(v: {tstr: tstr}) -> {tstr: tstr}``

        Args:
            v: ``{tstr: tstr}``.
            timeout: seconds to wait for the answer (default: the bridge client's).

        Returns:
            ``{tstr: tstr}``.

        Raises:
            ArgumentError: an argument does not match the contract (nothing is sent).
            ProviderRejection: the provider refused the call.
                This return type can hold a value shaped like a refusal; such a value is
                reported as a rejection too.
            ResultDecodeError: the result does not match the contract.
            MethodNotFound: this bridge does not expose the method.
        """
        return self._portal.call(self._aio.echo_string_map, v, timeout=timeout)

    def echo_nested_ints(
        self,
        v: _abc.Sequence[_abc.Sequence[int]],
        *,
        timeout: float | None = None,
    ) -> list[list[int]]:
        """Call ``test_fullapi_ext_cpp.echoNestedInts``.

        LIDL: ``method echoNestedInts(v: [[int]]) -> [[int]]``

        Args:
            v: ``[[int]]``.
            timeout: seconds to wait for the answer (default: the bridge client's).

        Returns:
            ``[[int]]``.

        Raises:
            ArgumentError: an argument does not match the contract (nothing is sent).
            ProviderRejection: the provider refused the call.
            ResultDecodeError: the result does not match the contract.
            MethodNotFound: this bridge does not expose the method.
        """
        return self._portal.call(self._aio.echo_nested_ints, v, timeout=timeout)

    def echo_map_of_bytes_lists(
        self,
        v: _abc.Mapping[str, _abc.Sequence[bytes]],
        *,
        timeout: float | None = None,
    ) -> dict[str, list[bytes]]:
        """Call ``test_fullapi_ext_cpp.echoMapOfBytesLists``.

        LIDL: ``method echoMapOfBytesLists(v: {tstr: [bstr]}) -> {tstr: [bstr]}``

        Args:
            v: ``{tstr: [bstr]}``.
            timeout: seconds to wait for the answer (default: the bridge client's).

        Returns:
            ``{tstr: [bstr]}``.

        Raises:
            ArgumentError: an argument does not match the contract (nothing is sent).
            ProviderRejection: the provider refused the call.
            ResultDecodeError: the result does not match the contract.
            MethodNotFound: this bridge does not expose the method.
        """
        return self._portal.call(self._aio.echo_map_of_bytes_lists, v, timeout=timeout)

    def echo_opt(self, v: Opt, *, timeout: float | None = None) -> Opt:
        """Call ``test_fullapi_ext_cpp.echoOpt``.

        LIDL: ``method echoOpt(v: Opt) -> Opt``

        Args:
            v: ``Opt``.
            timeout: seconds to wait for the answer (default: the bridge client's).

        Returns:
            ``Opt``.

        Raises:
            ArgumentError: an argument does not match the contract (nothing is sent).
            ProviderRejection: the provider refused the call.
            ResultDecodeError: the result does not match the contract.
            MethodNotFound: this bridge does not expose the method.
        """
        return self._portal.call(self._aio.echo_opt, v, timeout=timeout)

    def echo_opt_list(self, v: _abc.Sequence[Opt], *, timeout: float | None = None) -> list[Opt]:
        """Call ``test_fullapi_ext_cpp.echoOptList``.

        LIDL: ``method echoOptList(v: [Opt]) -> [Opt]``

        Args:
            v: ``[Opt]``.
            timeout: seconds to wait for the answer (default: the bridge client's).

        Returns:
            ``[Opt]``.

        Raises:
            ArgumentError: an argument does not match the contract (nothing is sent).
            ProviderRejection: the provider refused the call.
            ResultDecodeError: the result does not match the contract.
            MethodNotFound: this bridge does not expose the method.
        """
        return self._portal.call(self._aio.echo_opt_list, v, timeout=timeout)

    def echo_optional(self, v: str | None = None, *, timeout: float | None = None) -> str | None:
        """Call ``test_fullapi_ext_cpp.echoOptional``.

        LIDL: ``method echoOptional(v: ? tstr) -> ? tstr``

        Args:
            v: ``? tstr`` (optional).
            timeout: seconds to wait for the answer (default: the bridge client's).

        Returns:
            ``? tstr``.

        Raises:
            ArgumentError: an argument does not match the contract (nothing is sent).
            ProviderRejection: the provider refused the call.
            ResultDecodeError: the result does not match the contract.
            MethodNotFound: this bridge does not expose the method.
        """
        return self._portal.call(self._aio.echo_optional, v, timeout=timeout)

    def fire_blob_event(self, v: Blob, *, timeout: float | None = None) -> bool:
        """Call ``test_fullapi_ext_cpp.fireBlobEvent``.

        LIDL: ``method fireBlobEvent(v: Blob) -> bool``

        Args:
            v: ``Blob``.
            timeout: seconds to wait for the answer (default: the bridge client's).

        Returns:
            ``bool``.

        Raises:
            ArgumentError: an argument does not match the contract (nothing is sent).
            ProviderRejection: the provider refused the call.
            ResultDecodeError: the result does not match the contract.
            MethodNotFound: this bridge does not expose the method.
        """
        return self._portal.call(self._aio.fire_blob_event, v, timeout=timeout)

    def name(self, *, timeout: float | None = None) -> str:
        """The module's name, as declared in its metadata.

        LIDL: ``method name() -> tstr`` (derived built-in)

        Args:
            timeout: seconds to wait for the answer (default: the bridge client's).

        Returns:
            ``tstr``.

        Raises:
            ArgumentError: an argument does not match the contract (nothing is sent).
            ProviderRejection: the provider refused the call.
            ResultDecodeError: the result does not match the contract.
            MethodNotFound: this bridge does not expose the method.
        """
        return self._portal.call(self._aio.name, timeout=timeout)

    def version(self, *, timeout: float | None = None) -> str:
        """The module's version, as declared in its metadata.

        LIDL: ``method version() -> tstr`` (derived built-in)

        Args:
            timeout: seconds to wait for the answer (default: the bridge client's).

        Returns:
            ``tstr``.

        Raises:
            ArgumentError: an argument does not match the contract (nothing is sent).
            ProviderRejection: the provider refused the call.
            ResultDecodeError: the result does not match the contract.
            MethodNotFound: this bridge does not expose the method.
        """
        return self._portal.call(self._aio.version, timeout=timeout)

    def lidl(self, *, timeout: float | None = None) -> str:
        """The module's canonical LIDL interface document.

        LIDL: ``method lidl() -> tstr`` (derived built-in)

        Args:
            timeout: seconds to wait for the answer (default: the bridge client's).

        Returns:
            ``tstr``.

        Raises:
            ArgumentError: an argument does not match the contract (nothing is sent).
            ProviderRejection: the provider refused the call.
            ResultDecodeError: the result does not match the contract.
            MethodNotFound: this bridge does not expose the method.
        """
        return self._portal.call(self._aio.lidl, timeout=timeout)

    def on_blob_event(
        self,
        *,
        timeout: float | None = None,
        max_pending: int | None = None,
    ) -> _t.BlockingTypedSubscription[BlobEventEvent]:
        """Subscribe to ``blobEvent``; iterate the result, and close it (or use ``with``)."""
        request = self._aio.on_blob_event(timeout=timeout, max_pending=max_pending)
        return _t.BlockingTypedSubscription.open(request, self._portal)

    def decode_blob_event(self, event: _Event) -> BlobEventEvent:
        """Decode a raw ``blobEvent`` event."""
        return self._aio.decode_blob_event(event)

    def events(
        self,
        *names: TestFullapiExtCppEventName,
        timeout: float | None = None,
        max_pending: int | None = None,
    ) -> _t.BlockingTypedSubscription[TestFullapiExtCppEvent]:
        """One ordered, blocking stream of the named events (every event when none are named)."""
        request = self._aio.events(*names, timeout=timeout, max_pending=max_pending)
        return _t.BlockingTypedSubscription.open(request, self._portal)

    def check_compat(
        self,
        *,
        allow_untyped: bool = False,
        discovery_wait: float | None = 10.0,
    ) -> _CompatReport:
        """Blocking :meth:`AsyncTestFullapiExtCppClient.check_compat`."""
        return self._portal.call(
            self._aio.check_compat, allow_untyped=allow_untyped, discovery_wait=discovery_wait
        )
