"""``logos-bridge-codegen markdown``: a reference page for one contract.

Each method and event shows its LIDL signature, its description (Doxygen
``@code`` blocks become fenced blocks), a parameter table with the Python types
of the generated client, and a usage line; ``--py-accessor EXPR`` sets how that
line reaches the client (``client.raw``, say).
"""

from __future__ import annotations

from typing import Final

from .._version import __version__
from ..lidl import Interface, Method, Slot
from ..typed import rejection_ambiguous
from .naming import Names
from .python import Contract, _TypeSpeller
from .text import markdown_text, md_code

MARKDOWN_PROVENANCE: Final = ("<!-- Source: ",)


def _python_type(speller: _TypeSpeller, slot: Slot, *, param: bool) -> str:
    spelled = speller.slot(slot, param=param)
    for prefix in ("_typing.", "_abc.", "_builtins."):
        spelled = spelled.replace(prefix, "")
    return spelled.replace("_t.LogosResult", "LogosResult")


def _call(accessor: str, method: str, params: list[str], *, sync: bool) -> str:
    call = f"{accessor}.{method}({', '.join(params)})"
    return call if sync else f"await {call}"


def generate_markdown(contract: Contract, names: Names, *, py_accessor: str = "client") -> str:
    iface = contract.interface
    speller = _TypeSpeller(names, frozenset())
    out: list[str] = []
    add = out.append
    version = iface.version or "(no version)"
    add(f"<!-- GENERATED by logos-bridge-codegen from the LIDL contract {iface.name} {version}. Do not edit. -->")
    reader = f"; reader: {contract.reader}" if contract.reader else ""
    add(f"<!-- Source: {contract.source}; generator: logos-bridge {__version__}{reader} -->")
    add("")
    add(f"# {md_code(iface.name)}")
    add("")
    if iface.description:
        add(markdown_text(iface.description))
        add("")
    add("| | |")
    add("|---|---|")
    add(f"| Version | {md_code(version)} |")
    add(f"| Category | {md_code(iface.category) if iface.category else 'none'} |")
    add(f"| Depends on | {', '.join(md_code(d) for d in iface.depends) or 'nothing'} |")
    if iface.optional_depends:
        add(f"| Optionally depends on | {', '.join(md_code(d) for d in iface.optional_depends)} |")
    add(f"| Python clients | {md_code(names.async_client)}, {md_code(names.sync_client)} |")
    add(f"| `interface_sha256` | {md_code(iface.interface_sha256())} |")
    add(f"| `contract_sha256` | {md_code(contract.contract_sha256) if contract.contract_sha256 else 'unknown'} |")
    add(f"| `shape_sha256` | {md_code(iface.shape_sha256())} |")
    add("")
    add(f"Calls go through `rpc.call`; `{py_accessor}` is an `{names.async_client}` (await the calls)")
    add(f"or a `{names.sync_client}` (the same calls, blocking).")
    add("")

    if iface.methods:
        add("## Methods")
        add("")
        add("| Method | Python | Returns |")
        add("|---|---|---|")
        for method in iface.methods:
            py = names.methods[method.name]
            returns = "nothing" if method.returns is None else md_code(
                _python_type(speller, method.returns, param=False))
            add(f"| [{md_code(method.name)}](#method-{method.name}) | "
                f"{md_code(_call(py_accessor, py, names.params[method.name], sync=False))} | {returns} |")
        add("")
        for method in iface.methods:
            _method_section(out, method, names, speller, iface, py_accessor)

    if iface.events:
        add("## Events")
        add("")
        for event in iface.events:
            cls = names.event_classes[event.name]
            add(f'<a id="event-{event.name}"></a>')
            add("")
            add(f"### {md_code(event.name)}")
            add("")
            add("```lidl")
            add(f"event {event.signature()}")
            add("```")
            add("")
            if event.description:
                add(markdown_text(event.description))
                add("")
            if event.params:
                add("| Parameter | LIDL | Python attribute |")
                add("|---|---|---|")
                attrs = names.event_fields[event.name]
                for param in event.params:
                    add(f"| {md_code(param.name)} | {md_code(param.type.spell())} | "
                        f"{md_code(attrs[param.name] + ': ' + _python_type(speller, param, param=False))} |")
                add("")
            add(f"Python: `async with {py_accessor}.{names.subscriber(event.name)}() as events:` yields "
                f"{md_code(cls)}; `{py_accessor}.events({event.name!r})` merges it with others.")
            add("")

    if iface.types:
        add("## Records")
        add("")
        for record in iface.types:
            add(f'<a id="record-{record.name}"></a>')
            add("")
            add(f"### {md_code(record.name)}")
            add("")
            add(f"Python: the frozen dataclass {md_code(names.records[record.name])}. An empty optional "
                "field is left out of the JSON object.")
            add("")
            add("| Field | LIDL | Python attribute | Optional |")
            add("|---|---|---|---|")
            attrs = names.fields[record.name]
            for fd in record.fields:
                add(f"| {md_code(fd.name)} | {md_code(fd.spell())} | "
                    f"{md_code(attrs[fd.name] + ': ' + _python_type(speller, fd, param=False))} | "
                    f"{'yes' if fd.optional else 'no'} |")
            add("")
    return "\n".join(out).rstrip("\n") + "\n"


def _method_section(out: list[str], method: Method, names: Names, speller: _TypeSpeller, iface: Interface,
                    accessor: str) -> None:
    add = out.append
    py = names.methods[method.name]
    add(f'<a id="method-{method.name}"></a>')
    add("")
    add(f"### {md_code(method.name)}")
    add("")
    add("```lidl")
    add(f"method {method.signature()}")
    add("```")
    add("")
    if method.derived:
        add("A derived built-in: every module answers it, and no author writes it.")
        add("")
    if method.description:
        add(markdown_text(method.description))
        add("")
    if method.params:
        add("| Parameter | LIDL | Python |")
        add("|---|---|---|")
        for py_param, param in zip(names.params[method.name], method.params):
            optional = " (optional)" if param.optional else ""
            add(f"| {md_code(param.name)} | {md_code(param.type.spell())}{optional} | "
                f"{md_code(py_param + ': ' + _python_type(speller, param, param=True))} |")
        add("")
    if method.returns is None:
        add("**Returns** nothing (the provider answers `true`; Python gets `None`).")
    else:
        python = _python_type(speller, method.returns, param=False)
        add(f"**Returns** {md_code(method.returns.type.spell())} (Python {md_code(python)}).")
        if method.returns.value_type.name == "result" and method.returns.value_type.kind == "primitive":
            add("`success: false` is an answer, not an exception; `LogosResult.unwrap()` raises it.")
        if rejection_ambiguous(method.returns.type, iface):
            add("A legitimate value shaped like a provider refusal (`{code, message, origin}` with a known "
                "code) is reported as `ProviderRejection`.")
    add("")
    add(f"Python: {md_code(_call(accessor, py, names.params[method.name], sync=False))}")
    add("")
